import type { PageContent } from './types'
import { list, text } from './fields'

/** Страница премии. Номинации, дедлайн и «приём открыт» — в «Настройки → Премия». */
export const AWARD: PageContent = {
  slug: 'page-award',
  label: 'Премия — тексты',
  desc: 'Страница future-arch.md/award. Номинации, дедлайн и флаг «приём открыт» — в разделе «Настройки → Премия». Пустое поле = остаётся текст, который стоит на сайте сейчас.',
  sections: [
    {
      name: 'hero',
      label: '00 · Первый экран',
      fields: [
        text('eyebrow', 'Строка над заголовком', 'aEyebrow'),
        text('open', 'Метка «Приём заявок открыт»', 'aOpen'),
        text('lead', 'Текст под заголовком', 'aLead', true),
        text('deadlineLabel', 'Подпись «Заявки до»', 'aDeadlineLabel'),
        text('daysLeft', 'Осталось дней ({days} — число)', 'aDaysLeft'),
        text('winners', 'Подпись «Победители»', 'aWinners'),
        text('winnersText', 'Текст про победителей', 'aWinnersText'),
        text('choose', 'Подпись над выбором', 'aChoose'),
        text('award', 'Карточка «Премия» — заголовок', 'aAward'),
        text('awardNote', 'Карточка «Премия» — текст', 'aAwardNote'),
        text('student', 'Карточка «Студенческий конкурс» — заголовок', 'aStudent'),
        text('studentNote', 'Карточка «Студенческий конкурс» — текст', 'aStudentNote'),
        text('cta', 'Кнопка в шапке', 'aCta'),
        text('alt', 'Описание иллюстрации (alt)', 'aHeroAlt'),
      ],
    },
    {
      name: 'nominations',
      label: '01 · Номинации',
      desc: 'Сами номинации — в «Настройки → Премия».',
      fields: [
        text('label', 'Надзаголовок', 'aNomLabel'),
        text('title', 'Заголовок', 'aNomTitle'),
        text('text', 'Подпись справа', 'aNomText'),
      ],
    },
    {
      name: 'prize',
      label: '02 · Награда',
      fields: [
        text('label', 'Надзаголовок', 'aPrizeLabel'),
        text('title', 'Заголовок', 'aPrizeTitle'),
        list('items', 'Что получает победитель', 'Пункт', [{ name: 'text', label: 'Текст', area: true }], [
          { text: 'aPrize1' },
          { text: 'aPrize2' },
          { text: 'aPrize3' },
          { text: 'aPrize4' },
        ]),
      ],
    },
    {
      name: 'form',
      label: '03 · Заявка на премию',
      fields: [
        text('label', 'Надзаголовок', 'aFormLabel'),
        text('title', 'Заголовок', 'aFormTitle'),
        text('nomination', 'Поле «Номинация»', 'aNomination'),
        text('chooseNom', 'Пустой пункт списка номинаций', 'aChooseNom'),
        text('project', 'Поле «Название проекта»', 'aProject'),
        text('authors', 'Поле «Авторы проекта»', 'aAuthors'),
        text('authorsPh', 'Подсказка в поле авторов', 'aAuthorsPh'),
        text('company', 'Поле «Компания»', 'aCompany'),
        text('companyPh', 'Подсказка в поле компании', 'aCompanyPh'),
        text('location', 'Поле «Местоположение»', 'aLocation'),
        text('locationPh', 'Подсказка в поле местоположения', 'aLocationPh'),
        text('area', 'Поле «Площадь»', 'aArea'),
        text('areaPh', 'Подсказка в поле площади', 'aAreaPh'),
        text('year', 'Поле «Год реализации»', 'aYear'),
        text('yearPh', 'Подсказка в поле года', 'aYearPh'),
        text('desc', 'Поле «Описание проекта»', 'aDesc'),
        text('descPh', 'Подсказка в описании', 'aDescPh'),
        text('attach', 'Кнопка «Прикрепить файл»', 'aAttach'),
        text('filesHint', 'Подсказка о файлах', 'aFilesHint'),
        text('send', 'Кнопка отправки', 'aSend'),
        text('sentText', 'Текст после отправки ({nom} — номинация)', 'aSentText', true),
        text('again', 'Кнопка «Подать ещё одну»', 'aAgain'),
      ],
    },
    {
      name: 'student',
      label: '04 · Студенческий конкурс',
      fields: [
        text('label', 'Надзаголовок', 'aStudentsLabel'),
        text('title1', 'Заголовок — строка 1', 'aStudent1'),
        text('title2', 'Заголовок — строка 2', 'aStudent2'),
        text('question', 'Вопрос конкурса', 'aStudentQ'),
        text('text', 'Текст', 'aStudentText', true),
        text('author', 'Поле «Автор проекта»', 'aAuthor'),
        text('school', 'Поле «Учебное заведение»', 'aSchool'),
        text('faculty', 'Поле «Факультет»', 'aFaculty'),
        text('studyYear', 'Поле «Год начала учёбы»', 'aStudyYear'),
        text('locationPh', 'Подсказка в поле местоположения', 'aStudentLocationPh'),
        text('areaPh', 'Подсказка в поле площади', 'aStudentAreaPh'),
        text('send', 'Кнопка отправки', 'aStudentSend'),
        text('sentText', 'Текст после отправки', 'aStudentSent', true),
        text('alt', 'Описание иллюстрации (alt)', 'aStudentAlt'),
      ],
    },
  ],
}
