import type { PageContent } from './types'

/** Страница премии — /award. Номинации, жюри и дедлайн — в «Премия — настройки». */
export const AWARD: PageContent = {
  slug: 'content-award',
  label: 'Премия — тексты',
  desc: 'Номинации, жюри, дедлайн и таймер — в разделе «Премия — настройки». Здесь — тексты страницы.',
  sections: [
    {
      name: 'hero',
      label: '00 · Первый экран',
      fields: [
        { kind: 'text', name: 'eyebrow', label: 'Строка над заголовком', key: 'k259' },
        { kind: 'text', name: 'event', label: 'Название события', key: 'k477' },
        { kind: 'text', name: 'title1', label: 'Заголовок — строка 1', key: 'k478' },
        { kind: 'text', name: 'title2', label: 'Заголовок — строка 2', key: 'k479' },
        { kind: 'text', name: 'leadName', label: 'Лид — название премии', key: 'k480' },
        { kind: 'text', name: 'leadText', label: 'Лид — продолжение', key: 'k481', area: true },
        { kind: 'text', name: 'deadlineLine', label: 'Строка о дедлайне', key: 'k482' },
        { kind: 'text', name: 'countdownNote', label: 'Подпись под таймером', key: 'k264' },
        { kind: 'text', name: 'ctaCompany', label: 'Кнопка 1', key: 'k265' },
        { kind: 'text', name: 'ctaStudent', label: 'Кнопка 2', key: 'k266' },
      ],
    },
    {
      name: 'tracks',
      label: '02 · Кто может подать заявку',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k267' },
        { kind: 'text', name: 'title', label: 'Заголовок', key: 'k268' },
        { kind: 'text', name: 'aTitle', label: 'Трек 1 — заголовок', key: 'k269' },
        { kind: 'text', name: 'aText1', label: 'Трек 1 — абзац 1', key: 'k270', area: true },
        { kind: 'text', name: 'aText2', label: 'Трек 1 — абзац 2', key: 'k271', area: true },
        { kind: 'text', name: 'bTitle', label: 'Трек 2 — заголовок', key: 'k272' },
        { kind: 'text', name: 'bText1', label: 'Трек 2 — абзац 1', key: 'k273', area: true },
        { kind: 'text', name: 'bText2', label: 'Трек 2 — абзац 2', key: 'k274', area: true },
      ],
    },
    {
      name: 'nominations',
      label: '03 · Номинации — обрамление',
      desc: 'Сами номинации редактируются в «Премия — настройки». Здесь — заголовки вокруг них.',
      fields: [
        { kind: 'text', name: 'title', label: 'Заголовок', key: 'k277' },
        { kind: 'text', name: 'link', label: 'Подпись слева под сеткой', key: 'k279' },
      ],
    },
    {
      name: 'result',
      label: '04 · Что получает победитель',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k280' },
        { kind: 'text', name: 'title', label: 'Заголовок', key: 'k281' },
        { kind: 'text', name: 'item1', label: 'Пункт 1', key: 'k282' },
        { kind: 'text', name: 'item1Value', label: 'Пункт 1 — цифра', key: 'k442' },
        { kind: 'text', name: 'item1Unit', label: 'Пункт 1 — подпись к цифре', key: 'k283' },
        { kind: 'text', name: 'item2', label: 'Пункт 2', key: 'k284' },
        { kind: 'text', name: 'item3', label: 'Пункт 3', key: 'k285' },
        { kind: 'text', name: 'item4', label: 'Пункт 4', key: 'k492' },
      ],
    },
    {
      name: 'how',
      label: '05 · Как проходит отбор',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k288' },
        { kind: 'text', name: 'title', label: 'Заголовок', key: 'k289' },
        { kind: 'text', name: 'step1', label: 'Шаг 1', key: 'k493' },
        { kind: 'text', name: 'step2', label: 'Шаг 2', key: 'k291' },
        { kind: 'text', name: 'step3', label: 'Шаг 3', key: 'k292' },
        { kind: 'text', name: 'step4', label: 'Шаг 4', key: 'k293' },
        { kind: 'text', name: 'marquee1', label: 'Бегущая строка — пункт 1', key: 'k494' },
        { kind: 'text', name: 'marquee2', label: 'Бегущая строка — пункт 2', key: 'k495' },
        { kind: 'text', name: 'marquee3', label: 'Бегущая строка — пункт 3', key: 'k297' },
      ],
    },
    {
      name: 'form',
      label: '06 · Форма заявки',
      fields: [
        { kind: 'text', name: 'title1', label: 'Заголовок — строка 1', key: 'k298' },
        { kind: 'text', name: 'title2', label: 'Заголовок — строка 2', key: 'k496' },
        { kind: 'text', name: 'fieldName', label: 'Поле «Имя и фамилия»', key: 'k300' },
        { kind: 'text', name: 'fieldOrg', label: 'Поле «Компания / вуз»', key: 'k301' },
        { kind: 'text', name: 'fieldTrack', label: 'Поле «Куда подаёте»', key: 'k302' },
        { kind: 'text', name: 'fieldNomination', label: 'Поле «Номинация»', key: 'k303' },
        { kind: 'text', name: 'fieldEmail', label: 'Поле «E-mail»', key: 'k455' },
        { kind: 'text', name: 'fieldPhone', label: 'Поле «Телефон»', key: 'k120' },
        { kind: 'text', name: 'fieldUrl', label: 'Поле «Ссылка на материалы»', key: 'k305' },
        { kind: 'text', name: 'fieldDesc', label: 'Поле «Коротко о проекте»', key: 'k306' },
        { kind: 'text', name: 'hint', label: 'Подсказка о материалах', key: 'k307', area: true },
        { kind: 'text', name: 'submit', label: 'Кнопка отправки', key: 'k121' },
        { kind: 'text', name: 'sentTitle', label: 'Заголовок после отправки', key: 'k122' },
        { kind: 'text', name: 'sentText', label: 'Текст после отправки', key: 'k308', area: true },
        { kind: 'text', name: 'outro', label: 'Фраза перед подвалом', key: 'k309' },
      ],
    },
  ],
}
