import type { PageContent } from './types'

/** Страница форума — /forum. */
export const FORUM: PageContent = {
  slug: 'content-forum',
  label: 'Форум — тексты',
  desc: 'Дата форума и показ таймера живут в разделе «Форум — настройки». Здесь — тексты.',
  sections: [
    {
      name: 'hero',
      label: '00 · Первый экран',
      fields: [
        { kind: 'text', name: 'year', label: 'Год', key: 'k467' },
        { kind: 'text', name: 'place', label: 'Город и страна', key: 'k137' },
        { kind: 'text', name: 'format', label: 'Формат мероприятия', key: 'k138' },
        { kind: 'text', name: 'title1', label: 'Заголовок — строка 1', key: 'k401' },
        { kind: 'text', name: 'title2', label: 'Заголовок — строка 2', key: 'k440' },
        { kind: 'text', name: 'claim', label: 'Ключевая фраза', key: 'k468' },
        { kind: 'text', name: 'ctaApply', label: 'Кнопка 1', key: 'k140' },
        { kind: 'text', name: 'ctaPartner', label: 'Кнопка 2', key: 'k141' },
        { kind: 'text', name: 'status', label: 'Статус приёма заявок', key: 'k142' },
        { kind: 'text', name: 'countdownNote', label: 'Подпись под таймером', key: 'k147' },
        { kind: 'text', name: 'dateLine', label: 'Дата и город под таймером', key: 'k148' },
      ],
    },
    {
      name: 'marquee',
      label: '00 · Бегущая строка',
      fields: [
        { kind: 'text', name: 'm1', label: 'Пункт 1', key: 'k149' },
        { kind: 'text', name: 'm2', label: 'Пункт 2', key: 'k150' },
        { kind: 'text', name: 'm3', label: 'Пункт 3', key: 'k151' },
        { kind: 'text', name: 'm4', label: 'Пункт 4', key: 'k152' },
        { kind: 'text', name: 'm5', label: 'Пункт 5', key: 'k153' },
        { kind: 'text', name: 'm6', label: 'Пункт 6', key: 'k154' },
        { kind: 'text', name: 'm7', label: 'Пункт 7', key: 'k155' },
        { kind: 'text', name: 'm8', label: 'Пункт 8', key: 'k156' },
      ],
    },
    {
      name: 'chain',
      label: '01 · Цепочка стоимости',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k163' },
        { kind: 'text', name: 'title', label: 'Заголовок', key: 'k164' },
        { kind: 'text', name: 'text', label: 'Текст', key: 'k165', area: true },
        { kind: 'text', name: 'note', label: 'Подпись под текстом', key: 'k166' },
        { kind: 'text', name: 'note2', label: 'Подпись к схеме', key: 'k167' },
        { kind: 'text', name: 'tag2', label: 'Слово в анимации — Среда', key: 'k158' },
        { kind: 'text', name: 'tag3', label: 'Слово в анимации — Ликвидность', key: 'k159' },
        { kind: 'text', name: 'tag4', label: 'Слово в анимации — Инфраструктура', key: 'k160' },
        { kind: 'text', name: 'tag5', label: 'Слово в анимации — Ценность', key: 'k161' },
        { kind: 'text', name: 'tag6', label: 'Слово в анимации — Контекст', key: 'k162' },
        {
          kind: 'list',
          name: 'stages',
          label: 'Этапы жизни объекта',
          itemLabel: 'Этап',
          cols: [
            { name: 'title', label: 'Этап' },
            { name: 'role', label: 'Кто отвечает' },
          ],
          rows: [
            { title: 'k168', role: 'k169' },
            { title: 'k170', role: 'k171' },
            { title: 'k157', role: 'k172' },
            { title: 'k173', role: 'k174' },
            { title: 'k175', role: 'k176' },
            { title: 'k177', role: 'k178' },
          ],
        },
      ],
    },
    {
      name: 'hall',
      label: '02 · Состав зала',
      fields: [
        { kind: 'text', name: 'label', label: 'Заголовок', key: 'k182' },
        { kind: 'text', name: 'statValue', label: 'Цифра', key: 'k442' },
        { kind: 'text', name: 'statLabel', label: 'Подпись к цифре', key: 'k79' },
        { kind: 'text', name: 'entry', label: 'Условие участия', key: 'k150' },
        {
          kind: 'list',
          name: 'groups',
          label: 'Кто в зале',
          itemLabel: 'Группа',
          cols: [
            { name: 'title', label: 'Группа' },
            { name: 'share', label: 'Доля' },
          ],
          rows: [
            { title: 'k184', share: 'k470' },
            { title: 'k59', share: 'k471' },
            { title: 'k57', share: 'k472' },
            { title: 'k53', share: 'k473' },
            { title: 'k185', share: 'k474' },
          ],
        },
      ],
    },
    {
      name: 'topics',
      label: '03 · Темы программы',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k194' },
        { kind: 'text', name: 'title1', label: 'Заголовок — строка 1', key: 'k195' },
        { kind: 'text', name: 'title2', label: 'Заголовок — строка 2', key: 'k196' },
        {
          kind: 'list',
          name: 'items',
          label: 'Темы',
          itemLabel: 'Тема',
          cols: [
            { name: 'tag', label: 'Метка' },
            { name: 'title', label: 'Заголовок' },
            { name: 'text', label: 'Описание', area: true },
          ],
          rows: [
            { tag: 'k175', title: 'k197', text: 'k198' },
            { tag: 'k199', title: 'k200', text: 'k201' },
            { tag: 'k30', title: 'k202', text: 'k203' },
            { tag: 'k204', title: 'k205', text: 'k206' },
          ],
        },
      ],
    },
    {
      name: 'program',
      label: '04 · Программа дня и спикеры',
      fields: [
        { kind: 'text', name: 'title', label: 'Заголовок', key: 'k207' },
        { kind: 'text', name: 'note', label: 'Подпись под заголовком', key: 'k210' },
        {
          kind: 'list',
          name: 'items',
          label: 'Пункты программы',
          itemLabel: 'Пункт',
          cols: [{ name: 'title', label: 'Пункт' }],
          rows: [
            { title: 'k211' },
            { title: 'k132' },
            { title: 'k133' },
            { title: 'k213' },
            { title: 'k135' },
            { title: 'k215' },
            { title: 'k136' },
            { title: 'k216' },
          ],
        },
        { kind: 'text', name: 'speakersTitle', label: 'Спикеры — заголовок', key: 'k217' },
        { kind: 'text', name: 'speakersNote', label: 'Спикеры — подпись справа', key: 'k219' },
        { kind: 'text', name: 'slotTitle', label: 'Свободное место — подпись', key: 'k320' },
      ],
    },
    {
      name: 'award',
      label: '05 · Блок премии',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k220' },
        { kind: 'text', name: 'title2', label: 'Заголовок — вторая строка', key: 'k221' },
        { kind: 'text', name: 'text1', label: 'Премия отрасли — описание', key: 'k222', area: true },
        { kind: 'text', name: 'text2', label: 'Студенческий конкурс — описание', key: 'k223', area: true },
        { kind: 'text', name: 'note', label: 'Подпись', key: 'k224' },
        { kind: 'text', name: 'cta', label: 'Кнопка', key: 'k225' },
      ],
    },
    {
      name: 'participation',
      label: '06 · Как участвовать',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k97' },
        { kind: 'text', name: 'title1', label: 'Заголовок — строка 1', key: 'k227' },
        { kind: 'text', name: 'title2', label: 'Заголовок — строка 2', key: 'k228' },
        { kind: 'text', name: 'text', label: 'Текст', key: 'k229', area: true },
        { kind: 'text', name: 'aLabel', label: 'Карточка 1 — метка', key: 'k230' },
        { kind: 'text', name: 'aTitle', label: 'Карточка 1 — заголовок', key: 'k231' },
        { kind: 'text', name: 'aItem1', label: 'Карточка 1 — пункт 1', key: 'k232' },
        { kind: 'text', name: 'aItem2', label: 'Карточка 1 — пункт 2', key: 'k233' },
        { kind: 'text', name: 'aItem3', label: 'Карточка 1 — пункт 3', key: 'k234' },
        { kind: 'text', name: 'aItem4', label: 'Карточка 1 — пункт 4', key: 'k235' },
        { kind: 'text', name: 'aCta', label: 'Карточка 1 — кнопка', key: 'k140' },
        { kind: 'text', name: 'bLabel', label: 'Карточка 2 — метка', key: 'k236' },
        { kind: 'text', name: 'bTitle', label: 'Карточка 2 — заголовок', key: 'k237' },
        { kind: 'text', name: 'bText', label: 'Карточка 2 — описание', key: 'k238', area: true },
        { kind: 'text', name: 'bItem1', label: 'Карточка 2 — пункт 1', key: 'k314' },
        { kind: 'text', name: 'bItem2', label: 'Карточка 2 — пункт 2', key: 'k239' },
        { kind: 'text', name: 'bCta', label: 'Карточка 2 — кнопка', key: 'k240' },
        { kind: 'text', name: 'bNote', label: 'Карточка 2 — подпись', key: 'k241' },
        { kind: 'text', name: 'outro', label: 'Фраза перед подвалом', key: 'k242' },
      ],
    },
    {
      name: 'form',
      label: '07 · Форма заявки',
      fields: [
        { kind: 'text', name: 'sideWord', label: 'Вертикальная надпись сбоку', key: 'k476' },
        { kind: 'text', name: 'title1', label: 'Заголовок — строка 1', key: 'k245' },
        { kind: 'text', name: 'title2', label: 'Заголовок — строка 2', key: 'k246' },
        { kind: 'text', name: 'note', label: 'Подпись под заголовком', key: 'k247' },
        { kind: 'text', name: 'note2', label: 'Подпись о презентации', key: 'k248', area: true },
        { kind: 'text', name: 'fieldName', label: 'Поле «Имя»', key: 'k112' },
        { kind: 'text', name: 'fieldCompany', label: 'Поле «Компания»', key: 'k113' },
        { kind: 'text', name: 'fieldEmail', label: 'Поле «E-mail»', key: 'k455' },
        { kind: 'text', name: 'fieldPhone', label: 'Поле «Телефон»', key: 'k120' },
        { kind: 'text', name: 'fieldKind', label: 'Поле «Тип обращения»', key: 'k249' },
        { kind: 'text', name: 'selectPlaceholder', label: 'Плейсхолдер выпадающих списков', key: 'k115' },
        { kind: 'text', name: 'optionArchitect', label: 'Позиция — вариант 1', key: 'k116' },
        { kind: 'text', name: 'optionDeveloper', label: 'Позиция — вариант 2', key: 'k117' },
        { kind: 'text', name: 'optionManufacturer', label: 'Позиция — вариант 3', key: 'k118' },
        { kind: 'text', name: 'optionInvestor', label: 'Позиция — вариант 4', key: 'k119' },
        { kind: 'text', name: 'submit', label: 'Кнопка отправки', key: 'k121' },
        { kind: 'text', name: 'sentTitle', label: 'Заголовок после отправки', key: 'k122' },
        { kind: 'text', name: 'sentText', label: 'Текст после отправки', key: 'k250', area: true },
      ],
    },
  ],
}
