import type { PageContent } from './types'
import { list, text } from './fields'

/** Главная — сообщество. Порядок секций = порядок на странице. */
export const HOME: PageContent = {
  slug: 'home',
  label: 'Главная — тексты',
  desc: 'Страница future-arch.md. Пустое поле = остаётся текст, который стоит на сайте сейчас.',
  sections: [
    {
      name: 'hero',
      label: '00 · Первый экран',
      fields: [
        text('eyebrow', 'Строка над заголовком', 'hEyebrow'),
        text('place', 'Город и год', 'hPlace'),
        text('lead', 'Текст под заголовком', 'hLead', true),
        text('beResident', 'Кнопка «Стать резидентом»', 'hBeResident'),
        text('bePartner', 'Кнопка «Стать партнёром»', 'hBePartner'),
        text('word1', 'Слово внизу 1', 'hWord1'),
        text('word2', 'Слово внизу 2', 'hWord2'),
        text('word3', 'Слово внизу 3', 'hWord3'),
        text('cta', 'Кнопка в шапке', 'hCta'),
        text('ctaMenu', 'Кнопка в мобильном меню', 'hCtaMenu'),
      ],
    },
    {
      name: 'mission',
      label: '01 · Миссия',
      fields: [
        text('label', 'Надзаголовок', 'hMissionLabel'),
        text('title', 'Заголовок', 'hMissionTitle'),
        text('text', 'Текст', 'hMissionText', true),
        list('values', 'Ценности', 'Ценность', [{ name: 'title', label: 'Название' }, { name: 'text', label: 'Описание', area: true }], [
          { title: 'hValue1', text: 'hValue1Text' },
          { title: 'hValue2', text: 'hValue2Text' },
          { title: 'hValue3', text: 'hValue3Text' },
          { title: 'hValue4', text: 'hValue4Text' },
        ]),
      ],
    },
    {
      name: 'who',
      label: '02 · Кто внутри',
      fields: [
        text('label', 'Надзаголовок', 'hWhoLabel'),
        text('title', 'Заголовок', 'hWhoTitle'),
        text('note', 'Подпись справа', 'hWhoNote'),
        text('residents', 'Резиденты — метка', 'hResidents'),
        text('residentsTerm', 'Резиденты — условие', 'hResidentsTerm'),
        text('residentsTitle', 'Резиденты — заголовок', 'hResidentsTitle'),
        list('perks', 'Резиденты — что получают', 'Пункт', [{ name: 'text', label: 'Текст' }], [
          { text: 'hPerk1' },
          { text: 'hPerk2' },
          { text: 'hPerk3' },
          { text: 'hPerk4' },
          { text: 'hPerk5' },
        ]),
        text('residentsLink', 'Резиденты — ссылка', 'hBeResidentArrow'),
        text('partners', 'Партнёры — метка', 'hPartners'),
        text('partnersTerm', 'Партнёры — условие', 'hPartnersTerm'),
        text('partnersTitle', 'Партнёры — заголовок', 'hPartnersTitle'),
        text('partnersText', 'Партнёры — текст', 'hPartnersText', true),
        text('partnersLink', 'Партнёры — ссылка', 'hBePartnerArrow'),
      ],
    },
    {
      name: 'formats',
      label: '03 · Форматы',
      fields: [
        text('label', 'Надзаголовок', 'hFormatsLabel'),
        text('title', 'Заголовок', 'hFormatsTitle'),
        list('items', 'Форматы', 'Формат', [{ name: 'title', label: 'Название' }, { name: 'text', label: 'Описание' }], [
          { title: 'hFormat1', text: 'hFormat1Text' },
          { title: 'hFormat2', text: 'hFormat2Text' },
          { title: 'hFormat3', text: 'hFormat3Text' },
          { title: 'hFormat4', text: 'hFormat4Text' },
          { title: 'hFormat5', text: 'hFormat5Text' },
          { title: 'hFormat6', text: 'hFormat6Text' },
          { title: 'hFormat7', text: 'hFormat7Text' },
          { title: 'hFormat8', text: 'hFormat8Text' },
          { title: 'hFormat9', text: 'hFormat9Text' },
        ]),
      ],
    },
    {
      name: 'join',
      label: '04 · Вступление и форма',
      fields: [
        text('label', 'Надзаголовок', 'hJoinLabel'),
        text('title', 'Заголовок', 'hJoinTitle'),
        text('text', 'Текст', 'hJoinText', true),
        text('resident', 'Переключатель «Резидент»', 'hResident'),
        text('partnersShort', 'Партнёры — кратко', 'hPartnersShort'),
        text('empQuestion', 'Вопрос о месте работы', 'hEmpQuestion'),
        text('empSelf', 'Ответ «на себя»', 'hEmpSelf'),
        text('empCompany', 'Ответ «в компании»', 'hEmpCompany'),
        text('whichCompany', 'Поле «В какой компании»', 'hWhichCompany'),
        text('studioName', 'Поле «Название студии»', 'hStudioName'),
        text('optional', 'Подсказка «Необязательно»', 'hOptional'),
        text('profession', 'Поле «Профессия»', 'hProfession'),
        text('professionPh', 'Подсказка в поле «Профессия»', 'hProfessionPh'),
        text('field', 'Поле «Направление деятельности»', 'hField'),
        text('site', 'Поле «Сайт»', 'hSite'),
        text('sendPartner', 'Кнопка для партнёра', 'hSendPartner'),
        text('sentText', 'Текст после отправки', 'hSentText', true),
      ],
    },
  ],
}
