import type { PageContent } from './types'

/** Главная страница — сообщество. */
export const HOME: PageContent = {
  slug: 'content-home',
  label: 'Главная — тексты',
  desc: 'Страница future-arch.md. Пустое поле = остаётся текст, который стоит на сайте сейчас.',
  sections: [
    {
      name: 'hero',
      label: '00 · Первый экран',
      fields: [
        { kind: 'text', name: 'eyebrow', label: 'Строка над заголовком', key: 'k34' },
        { kind: 'text', name: 'title1', label: 'Заголовок — первая строка', key: 'k412' },
        { kind: 'text', name: 'title2', label: 'Заголовок — вторая строка', key: 'k413' },
        { kind: 'text', name: 'kicker', label: 'Подпись слева', key: 'k414' },
        { kind: 'text', name: 'entry', label: 'Подпись справа', key: 'k36' },
        { kind: 'text', name: 'note', label: 'Пояснение под заголовком', key: 'k415', area: true },
      ],
    },
    {
      name: 'tags',
      label: '00 · Теги в шапке и бегущая строка',
      desc: 'Короткие слова, которые крутятся в первом экране и в бегущей строке.',
      fields: [
        { kind: 'text', name: 'tagArchitecture', label: 'Архитектура', key: 'k39' },
        { kind: 'text', name: 'tagDesign', label: 'Дизайн', key: 'k418' },
        { kind: 'text', name: 'tagInterior', label: 'Дизайн интерьера', key: 'k407' },
        { kind: 'text', name: 'tagUrban', label: 'Градостроительство', key: 'k28' },
        { kind: 'text', name: 'tagPractice', label: 'Независимая практика', key: 'k24' },
        { kind: 'text', name: 'tagStudios', label: 'Бюро и студии', key: 'k27' },
        { kind: 'text', name: 'tagCircle', label: 'Закрытый круг', key: 'k43' },
        { kind: 'text', name: 'tagRecs', label: 'Рекомендации', key: 'k408' },
        { kind: 'text', name: 'tagArchiminds', label: 'ArchiMinds', key: 'k409' },
        { kind: 'text', name: 'tagExpertise', label: 'Экспертиза', key: 'k410' },
        { kind: 'text', name: 'tagNetworking', label: 'Нетворкинг', key: 'k411' },
        { kind: 'text', name: 'tagCity', label: 'Кишинёв', key: 'k151' },
        { kind: 'text', name: 'tagCountry', label: 'Молдова', key: 'k419' },
      ],
    },
    {
      name: 'position',
      label: '01 · Позиция',
      fields: [
        { kind: 'text', name: 'title1', label: 'Заголовок — строка 1', key: 'k39', desc: 'Это же слово используется в тегах шапки.' },
        { kind: 'text', name: 'title2', label: 'Заголовок — строка 2', key: 'k45' },
        { kind: 'text', name: 'title3', label: 'Заголовок — строка 3', key: 'k46' },
        { kind: 'text', name: 'text', label: 'Текст', key: 'k421', area: true },
      ],
    },
    {
      name: 'composition',
      label: '02 · Кто внутри сообщества',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k18' },
        { kind: 'text', name: 'title1', label: 'Заголовок — строка 1', key: 'k315' },
        { kind: 'text', name: 'title2', label: 'Заголовок — строка 2', key: 'k316' },
        { kind: 'text', name: 'residentsLabel', label: 'Подпись группы 1', key: 'k423' },
        { kind: 'text', name: 'residentsTitle1', label: 'Группа 1 — строка 1', key: 'k21' },
        { kind: 'text', name: 'residentsTitle2', label: 'Группа 1 — строка 2', key: 'k424' },
        { kind: 'text', name: 'residentsText', label: 'Группа 1 — описание', key: 'k425', area: true },
        { kind: 'text', name: 'partnersTitle', label: 'Группа 2 — заголовок', key: 'k426', area: true },
        { kind: 'text', name: 'partnersText', label: 'Группа 2 — описание', key: 'k427', area: true },
      ],
    },
    {
      name: 'formats',
      label: '03 · Восемь форматов',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k61' },
        { kind: 'text', name: 'title1', label: 'Заголовок — строка 1', key: 'k62' },
        { kind: 'text', name: 'title2', label: 'Заголовок — строка 2', key: 'k63' },
        {
          kind: 'list',
          name: 'items',
          label: 'Форматы',
          itemLabel: 'Формат',
          desc: 'Порядок и количество зафиксированы вёрсткой — меняются названия и описания.',
          cols: [
            { name: 'title', label: 'Название' },
            { name: 'text', label: 'Описание', area: true },
          ],
          rows: [
            { title: 'k65', text: 'k66' },
            { title: 'k409', text: 'k67' },
            { title: 'k68', text: 'k69' },
            { title: 'k70', text: 'k430' },
            { title: 'k432', text: 'k433' },
            { title: 'k310', text: 'k435' },
            { title: 'k437', text: 'k311' },
            { title: 'k74', text: 'k439' },
          ],
        },
      ],
    },
    {
      name: 'forum',
      label: '04 · Блок форума',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k76' },
        { kind: 'text', name: 'venue', label: 'Площадка и дата', key: 'k77' },
        { kind: 'text', name: 'title1', label: 'Заголовок — строка 1', key: 'k401' },
        { kind: 'text', name: 'title2', label: 'Заголовок — строка 2', key: 'k440' },
        { kind: 'text', name: 'text', label: 'Описание', key: 'k441', area: true },
        { kind: 'text', name: 'statValue', label: 'Цифра', key: 'k442' },
        { kind: 'text', name: 'statLabel', label: 'Подпись к цифре', key: 'k79' },
        { kind: 'text', name: 'cta', label: 'Ссылка на страницу форума', key: 'k81' },
      ],
    },
    {
      name: 'founders',
      label: '05 · Основатели',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k82' },
        { kind: 'text', name: 'title', label: 'Заголовок', key: 'k443' },
        { kind: 'text', name: 'bureauLabel', label: 'Подпись бюро', key: 'k84' },
        { kind: 'text', name: 'bureauName', label: 'Название бюро', key: 'k444' },
        {
          kind: 'list',
          name: 'stats',
          label: 'Цифры бюро',
          itemLabel: 'Цифра',
          cols: [
            { name: 'value', label: 'Значение' },
            { name: 'label', label: 'Подпись' },
          ],
          rows: [
            { value: 'k445', label: 'k85' },
            { value: 'k446', label: 'k86' },
            { value: 'k447', label: 'k87' },
            { value: 'k448', label: 'k88' },
            { value: 'k449', label: 'k89' },
          ],
        },
        { kind: 'text', name: 'mediaLabel', label: 'Подпись медиа-партнёра', key: 'k90' },
        { kind: 'text', name: 'mediaName', label: 'Медиа-партнёр', key: 'k450' },
        { kind: 'text', name: 'mediaValue', label: 'Цифра медиа-партнёра', key: 'k451' },
        { kind: 'text', name: 'mediaText', label: 'Описание медиа-партнёра', key: 'k91', area: true },
      ],
    },
    {
      name: 'participation',
      label: '06 · Форматы участия',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k92' },
        { kind: 'text', name: 'title', label: 'Заголовок', key: 'k452' },
        { kind: 'text', name: 'residentTitle', label: 'Карточка 1 — заголовок', key: 'k453' },
        { kind: 'text', name: 'residentText', label: 'Карточка 1 — описание', key: 'k53' },
        { kind: 'text', name: 'partnerTitle', label: 'Карточка 2 — заголовок', key: 'k237' },
        { kind: 'text', name: 'terms', label: 'Подпись об условиях', key: 'k94' },
        { kind: 'text', name: 'partnerCta', label: 'Кнопка карточки 2', key: 'k104' },
        { kind: 'text', name: 'sideWord', label: 'Вертикальная надпись сбоку', key: 'k454' },
      ],
    },
    {
      name: 'form',
      label: '07 · Форма вступления',
      fields: [
        { kind: 'text', name: 'label', label: 'Надзаголовок', key: 'k20' },
        { kind: 'text', name: 'title1', label: 'Заголовок — строка 1', key: 'k105' },
        { kind: 'text', name: 'title2', label: 'Заголовок — строка 2', key: 'k106' },
        { kind: 'text', name: 'fieldName', label: 'Поле «Имя»', key: 'k112' },
        { kind: 'text', name: 'fieldCompany', label: 'Поле «Компания»', key: 'k113' },
        { kind: 'text', name: 'fieldRoleHint', label: 'Подсказка к полю «Позиция»', key: 'k312' },
        { kind: 'text', name: 'fieldEmail', label: 'Поле «E-mail»', key: 'k455' },
        { kind: 'text', name: 'fieldPhone', label: 'Поле «Телефон»', key: 'k120' },
        { kind: 'text', name: 'submit', label: 'Кнопка отправки', key: 'k121' },
        { kind: 'text', name: 'sentTitle', label: 'Заголовок после отправки', key: 'k122' },
        { kind: 'text', name: 'sentText', label: 'Текст после отправки', key: 'k123', area: true },
      ],
    },
  ],
}
