/* ARCH MAKERS — новая админка: разделы «Страницы» (home, forum, award, common)
   и «Настройки сайта» (settings). Каждое текстовое поле хранит RU/RO/EN рядом.
   Миграция только СОЗДАЁТ таблицы; данные переносит …_admin_data. */
import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TABLE "home_mission_values" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"title_ru" varchar,
  	"title_ro" varchar,
  	"title_en" varchar,
  	"text_ru" varchar,
  	"text_ro" varchar,
  	"text_en" varchar
  );
  
  CREATE TABLE "home_who_perks" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"text_ru" varchar,
  	"text_ro" varchar,
  	"text_en" varchar
  );
  
  CREATE TABLE "home_formats_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"title_ru" varchar,
  	"title_ro" varchar,
  	"title_en" varchar,
  	"text_ru" varchar,
  	"text_ro" varchar,
  	"text_en" varchar
  );
  
  CREATE TABLE "home" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"hero_eyebrow_ru" varchar,
  	"hero_eyebrow_ro" varchar,
  	"hero_eyebrow_en" varchar,
  	"hero_place_ru" varchar,
  	"hero_place_ro" varchar,
  	"hero_place_en" varchar,
  	"hero_lead_ru" varchar,
  	"hero_lead_ro" varchar,
  	"hero_lead_en" varchar,
  	"hero_be_resident_ru" varchar,
  	"hero_be_resident_ro" varchar,
  	"hero_be_resident_en" varchar,
  	"hero_be_partner_ru" varchar,
  	"hero_be_partner_ro" varchar,
  	"hero_be_partner_en" varchar,
  	"hero_word1_ru" varchar,
  	"hero_word1_ro" varchar,
  	"hero_word1_en" varchar,
  	"hero_word2_ru" varchar,
  	"hero_word2_ro" varchar,
  	"hero_word2_en" varchar,
  	"hero_word3_ru" varchar,
  	"hero_word3_ro" varchar,
  	"hero_word3_en" varchar,
  	"hero_cta_ru" varchar,
  	"hero_cta_ro" varchar,
  	"hero_cta_en" varchar,
  	"hero_cta_menu_ru" varchar,
  	"hero_cta_menu_ro" varchar,
  	"hero_cta_menu_en" varchar,
  	"mission_label_ru" varchar,
  	"mission_label_ro" varchar,
  	"mission_label_en" varchar,
  	"mission_title_ru" varchar,
  	"mission_title_ro" varchar,
  	"mission_title_en" varchar,
  	"mission_text_ru" varchar,
  	"mission_text_ro" varchar,
  	"mission_text_en" varchar,
  	"who_label_ru" varchar,
  	"who_label_ro" varchar,
  	"who_label_en" varchar,
  	"who_title_ru" varchar,
  	"who_title_ro" varchar,
  	"who_title_en" varchar,
  	"who_note_ru" varchar,
  	"who_note_ro" varchar,
  	"who_note_en" varchar,
  	"who_residents_ru" varchar,
  	"who_residents_ro" varchar,
  	"who_residents_en" varchar,
  	"who_residents_term_ru" varchar,
  	"who_residents_term_ro" varchar,
  	"who_residents_term_en" varchar,
  	"who_residents_title_ru" varchar,
  	"who_residents_title_ro" varchar,
  	"who_residents_title_en" varchar,
  	"who_residents_link_ru" varchar,
  	"who_residents_link_ro" varchar,
  	"who_residents_link_en" varchar,
  	"who_partners_ru" varchar,
  	"who_partners_ro" varchar,
  	"who_partners_en" varchar,
  	"who_partners_term_ru" varchar,
  	"who_partners_term_ro" varchar,
  	"who_partners_term_en" varchar,
  	"who_partners_title_ru" varchar,
  	"who_partners_title_ro" varchar,
  	"who_partners_title_en" varchar,
  	"who_partners_text_ru" varchar,
  	"who_partners_text_ro" varchar,
  	"who_partners_text_en" varchar,
  	"who_partners_link_ru" varchar,
  	"who_partners_link_ro" varchar,
  	"who_partners_link_en" varchar,
  	"formats_label_ru" varchar,
  	"formats_label_ro" varchar,
  	"formats_label_en" varchar,
  	"formats_title_ru" varchar,
  	"formats_title_ro" varchar,
  	"formats_title_en" varchar,
  	"join_label_ru" varchar,
  	"join_label_ro" varchar,
  	"join_label_en" varchar,
  	"join_title_ru" varchar,
  	"join_title_ro" varchar,
  	"join_title_en" varchar,
  	"join_text_ru" varchar,
  	"join_text_ro" varchar,
  	"join_text_en" varchar,
  	"join_resident_ru" varchar,
  	"join_resident_ro" varchar,
  	"join_resident_en" varchar,
  	"join_partners_short_ru" varchar,
  	"join_partners_short_ro" varchar,
  	"join_partners_short_en" varchar,
  	"join_emp_question_ru" varchar,
  	"join_emp_question_ro" varchar,
  	"join_emp_question_en" varchar,
  	"join_emp_self_ru" varchar,
  	"join_emp_self_ro" varchar,
  	"join_emp_self_en" varchar,
  	"join_emp_company_ru" varchar,
  	"join_emp_company_ro" varchar,
  	"join_emp_company_en" varchar,
  	"join_which_company_ru" varchar,
  	"join_which_company_ro" varchar,
  	"join_which_company_en" varchar,
  	"join_studio_name_ru" varchar,
  	"join_studio_name_ro" varchar,
  	"join_studio_name_en" varchar,
  	"join_optional_ru" varchar,
  	"join_optional_ro" varchar,
  	"join_optional_en" varchar,
  	"join_profession_ru" varchar,
  	"join_profession_ro" varchar,
  	"join_profession_en" varchar,
  	"join_profession_ph_ru" varchar,
  	"join_profession_ph_ro" varchar,
  	"join_profession_ph_en" varchar,
  	"join_field_ru" varchar,
  	"join_field_ro" varchar,
  	"join_field_en" varchar,
  	"join_site_ru" varchar,
  	"join_site_ro" varchar,
  	"join_site_en" varchar,
  	"join_send_partner_ru" varchar,
  	"join_send_partner_ro" varchar,
  	"join_send_partner_en" varchar,
  	"join_sent_text_ru" varchar,
  	"join_sent_text_ro" varchar,
  	"join_sent_text_en" varchar,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "forum_speakers" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"name_ru" varchar NOT NULL,
  	"name_ro" varchar,
  	"name_en" varchar,
  	"role_ru" varchar,
  	"role_ro" varchar,
  	"role_en" varchar,
  	"photo_id" integer
  );
  
  CREATE TABLE "forum_chain_stages" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"title_ru" varchar,
  	"title_ro" varchar,
  	"title_en" varchar
  );
  
  CREATE TABLE "forum_topics_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"tag_ru" varchar,
  	"tag_ro" varchar,
  	"tag_en" varchar,
  	"title_ru" varchar,
  	"title_ro" varchar,
  	"title_en" varchar,
  	"text_ru" varchar,
  	"text_ro" varchar,
  	"text_en" varchar
  );
  
  CREATE TABLE "forum_program_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"title_ru" varchar,
  	"title_ro" varchar,
  	"title_en" varchar
  );
  
  CREATE TABLE "forum" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"forum_date" timestamp(3) with time zone DEFAULT '2026-12-09T10:00:00+02:00',
  	"countdown_visible" boolean DEFAULT true,
  	"hero_date_place_ru" varchar,
  	"hero_date_place_ro" varchar,
  	"hero_date_place_en" varchar,
  	"hero_selection_ru" varchar,
  	"hero_selection_ro" varchar,
  	"hero_selection_en" varchar,
  	"hero_lead_ru" varchar,
  	"hero_lead_ro" varchar,
  	"hero_lead_en" varchar,
  	"hero_text_ru" varchar,
  	"hero_text_ro" varchar,
  	"hero_text_en" varchar,
  	"hero_cta_ru" varchar,
  	"hero_cta_ro" varchar,
  	"hero_cta_en" varchar,
  	"hero_cta_menu_ru" varchar,
  	"hero_cta_menu_ro" varchar,
  	"hero_cta_menu_en" varchar,
  	"hero_partner_offer_ru" varchar,
  	"hero_partner_offer_ro" varchar,
  	"hero_partner_offer_en" varchar,
  	"hero_days_ru" varchar,
  	"hero_days_ro" varchar,
  	"hero_days_en" varchar,
  	"hero_hours_ru" varchar,
  	"hero_hours_ro" varchar,
  	"hero_hours_en" varchar,
  	"hero_minutes_ru" varchar,
  	"hero_minutes_ro" varchar,
  	"hero_minutes_en" varchar,
  	"hero_seconds_ru" varchar,
  	"hero_seconds_ro" varchar,
  	"hero_seconds_en" varchar,
  	"chain_label_ru" varchar,
  	"chain_label_ro" varchar,
  	"chain_label_en" varchar,
  	"chain_title_ru" varchar,
  	"chain_title_ro" varchar,
  	"chain_title_en" varchar,
  	"chain_text_ru" varchar,
  	"chain_text_ro" varchar,
  	"chain_text_en" varchar,
  	"count_number_ru" varchar,
  	"count_number_ro" varchar,
  	"count_number_en" varchar,
  	"count_text_ru" varchar,
  	"count_text_ro" varchar,
  	"count_text_en" varchar,
  	"topics_title_ru" varchar,
  	"topics_title_ro" varchar,
  	"topics_title_en" varchar,
  	"topics_speakers_ru" varchar,
  	"topics_speakers_ro" varchar,
  	"topics_speakers_en" varchar,
  	"program_title1_ru" varchar,
  	"program_title1_ro" varchar,
  	"program_title1_en" varchar,
  	"program_title2_ru" varchar,
  	"program_title2_ro" varchar,
  	"program_title2_en" varchar,
  	"partners_label_ru" varchar,
  	"partners_label_ro" varchar,
  	"partners_label_en" varchar,
  	"partners_title_ru" varchar,
  	"partners_title_ro" varchar,
  	"partners_title_en" varchar,
  	"partners_text_ru" varchar,
  	"partners_text_ro" varchar,
  	"partners_text_en" varchar,
  	"partners_benefit1_ru" varchar,
  	"partners_benefit1_ro" varchar,
  	"partners_benefit1_en" varchar,
  	"partners_benefit2_ru" varchar,
  	"partners_benefit2_ro" varchar,
  	"partners_benefit2_en" varchar,
  	"partners_before_ru" varchar,
  	"partners_before_ro" varchar,
  	"partners_before_en" varchar,
  	"partners_during_ru" varchar,
  	"partners_during_ro" varchar,
  	"partners_during_en" varchar,
  	"partners_after_ru" varchar,
  	"partners_after_ro" varchar,
  	"partners_after_en" varchar,
  	"partners_cta_ru" varchar,
  	"partners_cta_ro" varchar,
  	"partners_cta_en" varchar,
  	"apply_title_ru" varchar,
  	"apply_title_ro" varchar,
  	"apply_title_en" varchar,
  	"apply_date_ru" varchar,
  	"apply_date_ro" varchar,
  	"apply_date_en" varchar,
  	"apply_place_ru" varchar,
  	"apply_place_ro" varchar,
  	"apply_place_en" varchar,
  	"apply_guest_ru" varchar,
  	"apply_guest_ro" varchar,
  	"apply_guest_en" varchar,
  	"apply_company_role_ru" varchar,
  	"apply_company_role_ro" varchar,
  	"apply_company_role_en" varchar,
  	"apply_sent_text_ru" varchar,
  	"apply_sent_text_ro" varchar,
  	"apply_sent_text_en" varchar,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "award_nomination_list" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"kind_ru" varchar,
  	"kind_ro" varchar,
  	"kind_en" varchar,
  	"title_ru" varchar NOT NULL,
  	"title_ro" varchar,
  	"title_en" varchar
  );
  
  CREATE TABLE "award_prize_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"text_ru" varchar,
  	"text_ro" varchar,
  	"text_en" varchar
  );
  
  CREATE TABLE "award" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"deadline_date" timestamp(3) with time zone DEFAULT '2026-11-20T23:59:00+02:00',
  	"form_open" boolean DEFAULT true,
  	"form_closed_text_ru" varchar,
  	"form_closed_text_ro" varchar,
  	"form_closed_text_en" varchar,
  	"hero_eyebrow_ru" varchar,
  	"hero_eyebrow_ro" varchar,
  	"hero_eyebrow_en" varchar,
  	"hero_open_ru" varchar,
  	"hero_open_ro" varchar,
  	"hero_open_en" varchar,
  	"hero_lead_ru" varchar,
  	"hero_lead_ro" varchar,
  	"hero_lead_en" varchar,
  	"hero_deadline_label_ru" varchar,
  	"hero_deadline_label_ro" varchar,
  	"hero_deadline_label_en" varchar,
  	"hero_days_left_ru" varchar,
  	"hero_days_left_ro" varchar,
  	"hero_days_left_en" varchar,
  	"hero_winners_ru" varchar,
  	"hero_winners_ro" varchar,
  	"hero_winners_en" varchar,
  	"hero_winners_text_ru" varchar,
  	"hero_winners_text_ro" varchar,
  	"hero_winners_text_en" varchar,
  	"hero_choose_ru" varchar,
  	"hero_choose_ro" varchar,
  	"hero_choose_en" varchar,
  	"hero_award_ru" varchar,
  	"hero_award_ro" varchar,
  	"hero_award_en" varchar,
  	"hero_award_note_ru" varchar,
  	"hero_award_note_ro" varchar,
  	"hero_award_note_en" varchar,
  	"hero_student_ru" varchar,
  	"hero_student_ro" varchar,
  	"hero_student_en" varchar,
  	"hero_student_note_ru" varchar,
  	"hero_student_note_ro" varchar,
  	"hero_student_note_en" varchar,
  	"hero_cta_ru" varchar,
  	"hero_cta_ro" varchar,
  	"hero_cta_en" varchar,
  	"nominations_label_ru" varchar,
  	"nominations_label_ro" varchar,
  	"nominations_label_en" varchar,
  	"nominations_title_ru" varchar,
  	"nominations_title_ro" varchar,
  	"nominations_title_en" varchar,
  	"nominations_text_ru" varchar,
  	"nominations_text_ro" varchar,
  	"nominations_text_en" varchar,
  	"prize_label_ru" varchar,
  	"prize_label_ro" varchar,
  	"prize_label_en" varchar,
  	"prize_title_ru" varchar,
  	"prize_title_ro" varchar,
  	"prize_title_en" varchar,
  	"form_label_ru" varchar,
  	"form_label_ro" varchar,
  	"form_label_en" varchar,
  	"form_title_ru" varchar,
  	"form_title_ro" varchar,
  	"form_title_en" varchar,
  	"form_nomination_ru" varchar,
  	"form_nomination_ro" varchar,
  	"form_nomination_en" varchar,
  	"form_choose_nom_ru" varchar,
  	"form_choose_nom_ro" varchar,
  	"form_choose_nom_en" varchar,
  	"form_project_ru" varchar,
  	"form_project_ro" varchar,
  	"form_project_en" varchar,
  	"form_authors_ru" varchar,
  	"form_authors_ro" varchar,
  	"form_authors_en" varchar,
  	"form_authors_ph_ru" varchar,
  	"form_authors_ph_ro" varchar,
  	"form_authors_ph_en" varchar,
  	"form_company_ru" varchar,
  	"form_company_ro" varchar,
  	"form_company_en" varchar,
  	"form_company_ph_ru" varchar,
  	"form_company_ph_ro" varchar,
  	"form_company_ph_en" varchar,
  	"form_location_ru" varchar,
  	"form_location_ro" varchar,
  	"form_location_en" varchar,
  	"form_location_ph_ru" varchar,
  	"form_location_ph_ro" varchar,
  	"form_location_ph_en" varchar,
  	"form_area_ru" varchar,
  	"form_area_ro" varchar,
  	"form_area_en" varchar,
  	"form_area_ph_ru" varchar,
  	"form_area_ph_ro" varchar,
  	"form_area_ph_en" varchar,
  	"form_year_ru" varchar,
  	"form_year_ro" varchar,
  	"form_year_en" varchar,
  	"form_year_ph_ru" varchar,
  	"form_year_ph_ro" varchar,
  	"form_year_ph_en" varchar,
  	"form_desc_ru" varchar,
  	"form_desc_ro" varchar,
  	"form_desc_en" varchar,
  	"form_desc_ph_ru" varchar,
  	"form_desc_ph_ro" varchar,
  	"form_desc_ph_en" varchar,
  	"form_attach_ru" varchar,
  	"form_attach_ro" varchar,
  	"form_attach_en" varchar,
  	"form_files_hint_ru" varchar,
  	"form_files_hint_ro" varchar,
  	"form_files_hint_en" varchar,
  	"form_send_ru" varchar,
  	"form_send_ro" varchar,
  	"form_send_en" varchar,
  	"form_sent_text_ru" varchar,
  	"form_sent_text_ro" varchar,
  	"form_sent_text_en" varchar,
  	"form_again_ru" varchar,
  	"form_again_ro" varchar,
  	"form_again_en" varchar,
  	"student_label_ru" varchar,
  	"student_label_ro" varchar,
  	"student_label_en" varchar,
  	"student_title1_ru" varchar,
  	"student_title1_ro" varchar,
  	"student_title1_en" varchar,
  	"student_title2_ru" varchar,
  	"student_title2_ro" varchar,
  	"student_title2_en" varchar,
  	"student_question_ru" varchar,
  	"student_question_ro" varchar,
  	"student_question_en" varchar,
  	"student_text_ru" varchar,
  	"student_text_ro" varchar,
  	"student_text_en" varchar,
  	"student_author_ru" varchar,
  	"student_author_ro" varchar,
  	"student_author_en" varchar,
  	"student_school_ru" varchar,
  	"student_school_ro" varchar,
  	"student_school_en" varchar,
  	"student_faculty_ru" varchar,
  	"student_faculty_ro" varchar,
  	"student_faculty_en" varchar,
  	"student_study_year_ru" varchar,
  	"student_study_year_ro" varchar,
  	"student_study_year_en" varchar,
  	"student_location_ph_ru" varchar,
  	"student_location_ph_ro" varchar,
  	"student_location_ph_en" varchar,
  	"student_area_ph_ru" varchar,
  	"student_area_ph_ro" varchar,
  	"student_area_ph_en" varchar,
  	"student_send_ru" varchar,
  	"student_send_ro" varchar,
  	"student_send_en" varchar,
  	"student_sent_text_ru" varchar,
  	"student_sent_text_ro" varchar,
  	"student_sent_text_en" varchar,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "common" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"nav_community_ru" varchar,
  	"nav_community_ro" varchar,
  	"nav_community_en" varchar,
  	"nav_forum_ru" varchar,
  	"nav_forum_ro" varchar,
  	"nav_forum_en" varchar,
  	"nav_award_ru" varchar,
  	"nav_award_ro" varchar,
  	"nav_award_en" varchar,
  	"nav_contacts_ru" varchar,
  	"nav_contacts_ro" varchar,
  	"nav_contacts_en" varchar,
  	"nav_menu_ru" varchar,
  	"nav_menu_ro" varchar,
  	"nav_menu_en" varchar,
  	"nav_close_ru" varchar,
  	"nav_close_ro" varchar,
  	"nav_close_en" varchar,
  	"contacts_email1_ru" varchar,
  	"contacts_email1_ro" varchar,
  	"contacts_email1_en" varchar,
  	"contacts_email2_ru" varchar,
  	"contacts_email2_ro" varchar,
  	"contacts_email2_en" varchar,
  	"contacts_phone1_ru" varchar,
  	"contacts_phone1_ro" varchar,
  	"contacts_phone1_en" varchar,
  	"contacts_phone1_label_ru" varchar,
  	"contacts_phone1_label_ro" varchar,
  	"contacts_phone1_label_en" varchar,
  	"contacts_phone2_ru" varchar,
  	"contacts_phone2_ro" varchar,
  	"contacts_phone2_en" varchar,
  	"contacts_phone2_label_ru" varchar,
  	"contacts_phone2_label_ro" varchar,
  	"contacts_phone2_label_en" varchar,
  	"contacts_instagram_ru" varchar,
  	"contacts_instagram_ro" varchar,
  	"contacts_instagram_en" varchar,
  	"contacts_facebook_ru" varchar,
  	"contacts_facebook_ro" varchar,
  	"contacts_facebook_en" varchar,
  	"contacts_linkedin_ru" varchar,
  	"contacts_linkedin_ro" varchar,
  	"contacts_linkedin_en" varchar,
  	"footer_tagline_ru" varchar,
  	"footer_tagline_ro" varchar,
  	"footer_tagline_en" varchar,
  	"footer_email_label_ru" varchar,
  	"footer_email_label_ro" varchar,
  	"footer_email_label_en" varchar,
  	"footer_phone_label_ru" varchar,
  	"footer_phone_label_ro" varchar,
  	"footer_phone_label_en" varchar,
  	"footer_founders_ru" varchar,
  	"footer_founders_ro" varchar,
  	"footer_founders_en" varchar,
  	"footer_privacy_ru" varchar,
  	"footer_privacy_ro" varchar,
  	"footer_privacy_en" varchar,
  	"footer_copyright_ru" varchar,
  	"footer_copyright_ro" varchar,
  	"footer_copyright_en" varchar,
  	"forms_sent_ru" varchar,
  	"forms_sent_ro" varchar,
  	"forms_sent_en" varchar,
  	"forms_full_name_ru" varchar,
  	"forms_full_name_ro" varchar,
  	"forms_full_name_en" varchar,
  	"forms_company_name_ru" varchar,
  	"forms_company_name_ro" varchar,
  	"forms_company_name_en" varchar,
  	"forms_contact_person_ru" varchar,
  	"forms_contact_person_ro" varchar,
  	"forms_contact_person_en" varchar,
  	"forms_phone_ru" varchar,
  	"forms_phone_ro" varchar,
  	"forms_phone_en" varchar,
  	"forms_email_ru" varchar,
  	"forms_email_ro" varchar,
  	"forms_email_en" varchar,
  	"forms_partner_ru" varchar,
  	"forms_partner_ro" varchar,
  	"forms_partner_en" varchar,
  	"forms_send_ru" varchar,
  	"forms_send_ro" varchar,
  	"forms_send_en" varchar,
  	"forms_consent_ru" varchar,
  	"forms_consent_ro" varchar,
  	"forms_consent_en" varchar,
  	"forms_consent_link_ru" varchar,
  	"forms_consent_link_ro" varchar,
  	"forms_consent_link_en" varchar,
  	"forms_sending_ru" varchar,
  	"forms_sending_ro" varchar,
  	"forms_sending_en" varchar,
  	"forms_error_ru" varchar,
  	"forms_error_ro" varchar,
  	"forms_error_en" varchar,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "settings" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"mail_to" varchar DEFAULT 'marketing-team@lh47arch.com',
  	"subject_prefix" varchar DEFAULT '[future-arch.md]',
  	"autoreply" boolean DEFAULT true,
  	"autoreply_subject_ru" varchar,
  	"autoreply_subject_ro" varchar,
  	"autoreply_subject_en" varchar,
  	"autoreply_body_ru" varchar,
  	"autoreply_body_ro" varchar,
  	"autoreply_body_en" varchar,
  	"seo_home_title_ru" varchar,
  	"seo_home_title_ro" varchar,
  	"seo_home_title_en" varchar,
  	"seo_home_description_ru" varchar,
  	"seo_home_description_ro" varchar,
  	"seo_home_description_en" varchar,
  	"seo_home_image_id" integer,
  	"seo_forum_title_ru" varchar,
  	"seo_forum_title_ro" varchar,
  	"seo_forum_title_en" varchar,
  	"seo_forum_description_ru" varchar,
  	"seo_forum_description_ro" varchar,
  	"seo_forum_description_en" varchar,
  	"seo_forum_image_id" integer,
  	"seo_award_title_ru" varchar,
  	"seo_award_title_ro" varchar,
  	"seo_award_title_en" varchar,
  	"seo_award_description_ru" varchar,
  	"seo_award_description_ro" varchar,
  	"seo_award_description_en" varchar,
  	"seo_award_image_id" integer,
  	"analytics_enabled" boolean DEFAULT true,
  	"gtm_id" varchar,
  	"ga4_id" varchar,
  	"yandex_id" varchar,
  	"meta_pixel_id" varchar,
  	"search_console_token" varchar,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  ALTER TABLE "home_mission_values" ADD CONSTRAINT "home_mission_values_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."home"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "home_who_perks" ADD CONSTRAINT "home_who_perks_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."home"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "home_formats_items" ADD CONSTRAINT "home_formats_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."home"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "forum_speakers" ADD CONSTRAINT "forum_speakers_photo_id_media_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "forum_speakers" ADD CONSTRAINT "forum_speakers_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."forum"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "forum_chain_stages" ADD CONSTRAINT "forum_chain_stages_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."forum"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "forum_topics_items" ADD CONSTRAINT "forum_topics_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."forum"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "forum_program_items" ADD CONSTRAINT "forum_program_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."forum"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "award_nomination_list" ADD CONSTRAINT "award_nomination_list_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."award"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "award_prize_items" ADD CONSTRAINT "award_prize_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."award"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "settings" ADD CONSTRAINT "settings_seo_home_image_id_media_id_fk" FOREIGN KEY ("seo_home_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "settings" ADD CONSTRAINT "settings_seo_forum_image_id_media_id_fk" FOREIGN KEY ("seo_forum_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "settings" ADD CONSTRAINT "settings_seo_award_image_id_media_id_fk" FOREIGN KEY ("seo_award_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "home_mission_values_order_idx" ON "home_mission_values" USING btree ("_order");
  CREATE INDEX "home_mission_values_parent_id_idx" ON "home_mission_values" USING btree ("_parent_id");
  CREATE INDEX "home_who_perks_order_idx" ON "home_who_perks" USING btree ("_order");
  CREATE INDEX "home_who_perks_parent_id_idx" ON "home_who_perks" USING btree ("_parent_id");
  CREATE INDEX "home_formats_items_order_idx" ON "home_formats_items" USING btree ("_order");
  CREATE INDEX "home_formats_items_parent_id_idx" ON "home_formats_items" USING btree ("_parent_id");
  CREATE INDEX "forum_speakers_order_idx" ON "forum_speakers" USING btree ("_order");
  CREATE INDEX "forum_speakers_parent_id_idx" ON "forum_speakers" USING btree ("_parent_id");
  CREATE INDEX "forum_speakers_photo_idx" ON "forum_speakers" USING btree ("photo_id");
  CREATE INDEX "forum_chain_stages_order_idx" ON "forum_chain_stages" USING btree ("_order");
  CREATE INDEX "forum_chain_stages_parent_id_idx" ON "forum_chain_stages" USING btree ("_parent_id");
  CREATE INDEX "forum_topics_items_order_idx" ON "forum_topics_items" USING btree ("_order");
  CREATE INDEX "forum_topics_items_parent_id_idx" ON "forum_topics_items" USING btree ("_parent_id");
  CREATE INDEX "forum_program_items_order_idx" ON "forum_program_items" USING btree ("_order");
  CREATE INDEX "forum_program_items_parent_id_idx" ON "forum_program_items" USING btree ("_parent_id");
  CREATE INDEX "award_nomination_list_order_idx" ON "award_nomination_list" USING btree ("_order");
  CREATE INDEX "award_nomination_list_parent_id_idx" ON "award_nomination_list" USING btree ("_parent_id");
  CREATE INDEX "award_prize_items_order_idx" ON "award_prize_items" USING btree ("_order");
  CREATE INDEX "award_prize_items_parent_id_idx" ON "award_prize_items" USING btree ("_parent_id");
  CREATE INDEX "settings_seo_home_seo_home_image_idx" ON "settings" USING btree ("seo_home_image_id");
  CREATE INDEX "settings_seo_forum_seo_forum_image_idx" ON "settings" USING btree ("seo_forum_image_id");
  CREATE INDEX "settings_seo_award_seo_award_image_idx" ON "settings" USING btree ("seo_award_image_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "home_mission_values" CASCADE;
  DROP TABLE "home_who_perks" CASCADE;
  DROP TABLE "home_formats_items" CASCADE;
  DROP TABLE "home" CASCADE;
  DROP TABLE "forum_speakers" CASCADE;
  DROP TABLE "forum_chain_stages" CASCADE;
  DROP TABLE "forum_topics_items" CASCADE;
  DROP TABLE "forum_program_items" CASCADE;
  DROP TABLE "forum" CASCADE;
  DROP TABLE "award_nomination_list" CASCADE;
  DROP TABLE "award_prize_items" CASCADE;
  DROP TABLE "award" CASCADE;
  DROP TABLE "common" CASCADE;
  DROP TABLE "settings" CASCADE;`)
}
