/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'community-applications': CommunityApplication;
    'forum-applications': ForumApplication;
    'award-applications': AwardApplication;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'community-applications': CommunityApplicationsSelect<false> | CommunityApplicationsSelect<true>;
    'forum-applications': ForumApplicationsSelect<false> | ForumApplicationsSelect<true>;
    'award-applications': AwardApplicationsSelect<false> | AwardApplicationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    forum: Forum;
    award: Award;
    common: Common;
    settings: Setting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    forum: ForumSelect<false> | ForumSelect<true>;
    award: AwardSelect<false> | AwardSelect<true>;
    common: CommonSelect<false> | CommonSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    welcome: WelcomeWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Форма на главной странице: резиденты и партнёры.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-applications".
 */
export interface CommunityApplication {
  id: number;
  /**
   * Резидент или партнёр.
   */
  track?: string | null;
  name: string;
  company?: string | null;
  role?: string | null;
  employment?: string | null;
  field?: string | null;
  website?: string | null;
  email: string;
  phone?: string | null;
  status?: ('new' | 'progress' | 'accepted' | 'declined') | null;
  /**
   * Видна только в админке.
   */
  note?: string | null;
  lang?: string | null;
  source?: string | null;
  utm?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Форма на странице форума.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-applications".
 */
export interface ForumApplication {
  id: number;
  name: string;
  company: string;
  role?: string | null;
  kind?: string | null;
  email: string;
  phone?: string | null;
  status?: ('new' | 'progress' | 'accepted' | 'declined') | null;
  /**
   * Видна только в админке.
   */
  note?: string | null;
  lang?: string | null;
  source?: string | null;
  utm?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Форма на странице премии — премия и студенческий конкурс.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-applications".
 */
export interface AwardApplication {
  id: number;
  track?: string | null;
  nomination?: string | null;
  project?: string | null;
  name: string;
  org: string;
  faculty?: string | null;
  studyStart?: string | null;
  location?: string | null;
  area?: string | null;
  year?: string | null;
  email?: string | null;
  phone?: string | null;
  desc?: string | null;
  /**
   * Имя файла и ссылка, по одному в строке. Файлы лежат в закрытом хранилище: ссылка открывается, только когда вы вошли в админку.
   */
  files?: string | null;
  url?: string | null;
  status?: ('new' | 'progress' | 'accepted' | 'declined') | null;
  /**
   * Видна только в админке.
   */
  note?: string | null;
  lang?: string | null;
  source?: string | null;
  utm?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'community-applications';
        value: number | CommunityApplication;
      } | null)
    | ({
        relationTo: 'forum-applications';
        value: number | ForumApplication;
      } | null)
    | ({
        relationTo: 'award-applications';
        value: number | AwardApplication;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-applications_select".
 */
export interface CommunityApplicationsSelect<T extends boolean = true> {
  track?: T;
  name?: T;
  company?: T;
  role?: T;
  employment?: T;
  field?: T;
  website?: T;
  email?: T;
  phone?: T;
  status?: T;
  note?: T;
  lang?: T;
  source?: T;
  utm?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-applications_select".
 */
export interface ForumApplicationsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  role?: T;
  kind?: T;
  email?: T;
  phone?: T;
  status?: T;
  note?: T;
  lang?: T;
  source?: T;
  utm?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-applications_select".
 */
export interface AwardApplicationsSelect<T extends boolean = true> {
  track?: T;
  nomination?: T;
  project?: T;
  name?: T;
  org?: T;
  faculty?: T;
  studyStart?: T;
  location?: T;
  area?: T;
  year?: T;
  email?: T;
  phone?: T;
  desc?: T;
  files?: T;
  url?: T;
  status?: T;
  note?: T;
  lang?: T;
  source?: T;
  utm?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Все тексты главной страницы. Сохраните — и через пару секунд они на сайте.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero?: {
    eyebrow?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    place?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    lead?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    beResident?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    bePartner?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    word1?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    word2?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    word3?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    cta?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    ctaMenu?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  mission?: {
    label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    text?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    values?:
      | {
          title?: {
            ru?: string | null;
            ro?: string | null;
            en?: string | null;
          };
          text?: {
            ru?: string | null;
            ro?: string | null;
            en?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  who?: {
    label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    note?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    residents?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    residentsTerm?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    residentsTitle?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    perks?:
      | {
          text?: {
            ru?: string | null;
            ro?: string | null;
            en?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    residentsLink?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    partners?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    partnersTerm?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    partnersTitle?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    partnersText?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    partnersLink?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  formats?: {
    label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    items?:
      | {
          title?: {
            ru?: string | null;
            ro?: string | null;
            en?: string | null;
          };
          text?: {
            ru?: string | null;
            ro?: string | null;
            en?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  join?: {
    label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    text?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    resident?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    partnersShort?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    empQuestion?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    empSelf?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    empCompany?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    whichCompany?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    studioName?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    optional?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    profession?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    professionPh?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    field?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    site?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    sendPartner?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    sentText?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Дата, спикеры и все тексты страницы форума.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum".
 */
export interface Forum {
  id: number;
  /**
   * От неё считается таймер на странице.
   */
  forumDate?: string | null;
  countdownVisible?: boolean | null;
  /**
   * Порядок в списке = порядок на сайте (перетаскивайте за ⠿). Фото Волошина, Разлоги, Мырзы и Ионицэ уже встроены — загружать не нужно. Новому спикеру без фото сайт покажет инициалы.
   */
  speakers?:
    | {
        name: {
          ru: string;
          ro?: string | null;
          en?: string | null;
        };
        role?: {
          ru?: string | null;
          ro?: string | null;
          en?: string | null;
        };
        /**
         * Вертикальный кадр 4:5, от 800 px в ширину. Чёрно-белым сайт сделает сам.
         */
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  hero?: {
    datePlace?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    selection?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    lead?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    text?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    cta?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    ctaMenu?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    partnerOffer?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    days?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    hours?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    minutes?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    seconds?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  chain?: {
    label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    text?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    stages?:
      | {
          title?: {
            ru?: string | null;
            ro?: string | null;
            en?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  count?: {
    number?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    text?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  topics?: {
    title?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    items?:
      | {
          tag?: {
            ru?: string | null;
            ro?: string | null;
            en?: string | null;
          };
          title?: {
            ru?: string | null;
            ro?: string | null;
            en?: string | null;
          };
          text?: {
            ru?: string | null;
            ro?: string | null;
            en?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    speakers?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  program?: {
    title1?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title2?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    items?:
      | {
          title?: {
            ru?: string | null;
            ro?: string | null;
            en?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  partners?: {
    label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    text?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    benefit1?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    benefit2?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    before?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    during?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    after?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    cta?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  apply?: {
    title?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    date?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    place?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    guest?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    companyRole?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    sentText?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Приём заявок, номинации и все тексты страницы премии.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award".
 */
export interface Award {
  id: number;
  /**
   * Дата в первом экране и счётчик «осталось N дней».
   */
  deadlineDate?: string | null;
  formOpen?: boolean | null;
  formClosedText?: {
    ru?: string | null;
    ro?: string | null;
    en?: string | null;
  };
  /**
   * Появляются и карточками на странице, и в выпадающем списке формы. Номер ставится сам.
   */
  nominationList?:
    | {
        kind?: {
          ru?: string | null;
          ro?: string | null;
          en?: string | null;
        };
        title: {
          ru: string;
          ro?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  hero?: {
    eyebrow?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    open?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    lead?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    deadlineLabel?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    daysLeft?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    winners?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    winnersText?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    choose?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    award?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    awardNote?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    student?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    studentNote?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    cta?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  nominations?: {
    label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    text?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  prize?: {
    label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    items?:
      | {
          text?: {
            ru?: string | null;
            ro?: string | null;
            en?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  form?: {
    label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    nomination?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    chooseNom?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    project?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    authors?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    authorsPh?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    company?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    companyPh?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    location?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    locationPh?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    area?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    areaPh?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    year?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    yearPh?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    desc?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    descPh?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    attach?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    filesHint?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    send?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    sentText?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    again?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  student?: {
    label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title1?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    title2?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    question?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    text?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    author?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    school?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    faculty?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    studyYear?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    locationPh?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    areaPh?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    send?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    sentText?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * То, что одинаково на всех страницах: пункты меню, контакты в подвале, подписи в формах.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "common".
 */
export interface Common {
  id: number;
  nav?: {
    community?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    forum?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    award?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    contacts?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    menu?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    close?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  contacts?: {
    email1?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    email2?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    phone1?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    phone1Label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    phone2?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    phone2Label?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    /**
     * Полный адрес, https://… Пустое поле — иконки нет.
     */
    instagram?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    /**
     * Пустое поле — иконки нет.
     */
    facebook?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    /**
     * Пустое поле — иконки нет.
     */
    linkedin?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  footer?: {
    tagline?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    emailLabel?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    phoneLabel?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    founders?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    privacy?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    copyright?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  forms?: {
    sent?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    fullName?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    companyName?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    contactPerson?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    phone?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    email?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    partner?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    send?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    consent?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    consentLink?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    sending?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
    error?: {
      ru?: string | null;
      ro?: string | null;
      en?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Куда приходят заявки, SEO и счётчики.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Несколько адресов — через запятую.
   */
  mailTo?: string | null;
  /**
   * По нему удобно настроить фильтр в почте.
   */
  subjectPrefix?: string | null;
  autoreply?: boolean | null;
  autoreplySubject?: {
    ru?: string | null;
    ro?: string | null;
    en?: string | null;
  };
  /**
   * Обычный текст. Абзацы — пустой строкой.
   */
  autoreplyBody?: {
    ru?: string | null;
    ro?: string | null;
    en?: string | null;
  };
  seo?: {
    home?: {
      /**
       * До 60 знаков. Пусто — стоит заголовок по умолчанию.
       */
      title?: {
        ru?: string | null;
        ro?: string | null;
        en?: string | null;
      };
      /**
       * До 160 знаков. Пусто — описание по умолчанию.
       */
      description?: {
        ru?: string | null;
        ro?: string | null;
        en?: string | null;
      };
      /**
       * Пусто — стоит картинка по умолчанию.
       */
      image?: (number | null) | Media;
    };
    forum?: {
      /**
       * До 60 знаков. Пусто — стоит заголовок по умолчанию.
       */
      title?: {
        ru?: string | null;
        ro?: string | null;
        en?: string | null;
      };
      /**
       * До 160 знаков. Пусто — описание по умолчанию.
       */
      description?: {
        ru?: string | null;
        ro?: string | null;
        en?: string | null;
      };
      /**
       * Пусто — стоит картинка по умолчанию.
       */
      image?: (number | null) | Media;
    };
    award?: {
      /**
       * До 60 знаков. Пусто — стоит заголовок по умолчанию.
       */
      title?: {
        ru?: string | null;
        ro?: string | null;
        en?: string | null;
      };
      /**
       * До 160 знаков. Пусто — описание по умолчанию.
       */
      description?: {
        ru?: string | null;
        ro?: string | null;
        en?: string | null;
      };
      /**
       * Пусто — стоит картинка по умолчанию.
       */
      image?: (number | null) | Media;
    };
  };
  analyticsEnabled?: boolean | null;
  gtmId?: string | null;
  ga4Id?: string | null;
  yandexId?: string | null;
  metaPixelId?: string | null;
  /**
   * Только значение content из мета-тега.
   */
  searchConsoleToken?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        place?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        beResident?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        bePartner?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        word1?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        word2?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        word3?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        cta?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        ctaMenu?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  mission?:
    | T
    | {
        label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        text?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        values?:
          | T
          | {
              title?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              id?: T;
            };
      };
  who?:
    | T
    | {
        label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        note?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        residents?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        residentsTerm?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        residentsTitle?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        perks?:
          | T
          | {
              text?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              id?: T;
            };
        residentsLink?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        partners?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        partnersTerm?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        partnersTitle?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        partnersText?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        partnersLink?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  formats?:
    | T
    | {
        label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        items?:
          | T
          | {
              title?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              id?: T;
            };
      };
  join?:
    | T
    | {
        label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        text?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        resident?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        partnersShort?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        empQuestion?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        empSelf?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        empCompany?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        whichCompany?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        studioName?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        optional?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        profession?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        professionPh?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        field?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        site?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        sendPartner?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        sentText?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum_select".
 */
export interface ForumSelect<T extends boolean = true> {
  forumDate?: T;
  countdownVisible?: T;
  speakers?:
    | T
    | {
        name?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        role?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        photo?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        datePlace?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        selection?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        text?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        cta?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        ctaMenu?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        partnerOffer?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        days?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        hours?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        minutes?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        seconds?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  chain?:
    | T
    | {
        label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        text?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        stages?:
          | T
          | {
              title?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              id?: T;
            };
      };
  count?:
    | T
    | {
        number?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        text?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  topics?:
    | T
    | {
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        items?:
          | T
          | {
              tag?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              title?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              id?: T;
            };
        speakers?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  program?:
    | T
    | {
        title1?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title2?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        items?:
          | T
          | {
              title?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              id?: T;
            };
      };
  partners?:
    | T
    | {
        label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        text?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        benefit1?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        benefit2?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        before?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        during?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        after?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        cta?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  apply?:
    | T
    | {
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        date?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        place?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        guest?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        companyRole?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        sentText?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award_select".
 */
export interface AwardSelect<T extends boolean = true> {
  deadlineDate?: T;
  formOpen?: T;
  formClosedText?:
    | T
    | {
        ru?: T;
        ro?: T;
        en?: T;
      };
  nominationList?:
    | T
    | {
        kind?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        id?: T;
      };
  hero?:
    | T
    | {
        eyebrow?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        open?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        deadlineLabel?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        daysLeft?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        winners?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        winnersText?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        choose?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        award?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        awardNote?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        student?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        studentNote?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        cta?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  nominations?:
    | T
    | {
        label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        text?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  prize?:
    | T
    | {
        label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        items?:
          | T
          | {
              text?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              id?: T;
            };
      };
  form?:
    | T
    | {
        label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        nomination?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        chooseNom?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        project?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        authors?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        authorsPh?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        company?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        companyPh?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        location?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        locationPh?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        area?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        areaPh?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        year?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        yearPh?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        desc?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        descPh?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        attach?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        filesHint?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        send?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        sentText?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        again?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  student?:
    | T
    | {
        label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title1?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        title2?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        question?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        text?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        author?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        school?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        faculty?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        studyYear?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        locationPh?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        areaPh?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        send?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        sentText?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "common_select".
 */
export interface CommonSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        community?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        forum?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        award?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        contacts?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        menu?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        close?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  contacts?:
    | T
    | {
        email1?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        email2?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        phone1?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        phone1Label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        phone2?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        phone2Label?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        instagram?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        facebook?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        linkedin?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  footer?:
    | T
    | {
        tagline?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        emailLabel?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        phoneLabel?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        founders?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        privacy?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        copyright?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  forms?:
    | T
    | {
        sent?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        fullName?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        companyName?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        contactPerson?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        phone?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        email?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        partner?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        send?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        consent?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        consentLink?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        sending?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
        error?:
          | T
          | {
              ru?: T;
              ro?: T;
              en?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  mailTo?: T;
  subjectPrefix?: T;
  autoreply?: T;
  autoreplySubject?:
    | T
    | {
        ru?: T;
        ro?: T;
        en?: T;
      };
  autoreplyBody?:
    | T
    | {
        ru?: T;
        ro?: T;
        en?: T;
      };
  seo?:
    | T
    | {
        home?:
          | T
          | {
              title?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              description?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              image?: T;
            };
        forum?:
          | T
          | {
              title?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              description?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              image?: T;
            };
        award?:
          | T
          | {
              title?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              description?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                    en?: T;
                  };
              image?: T;
            };
      };
  analyticsEnabled?: T;
  gtmId?: T;
  ga4Id?: T;
  yandexId?: T;
  metaPixelId?: T;
  searchConsoleToken?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "welcome_widget".
 */
export interface WelcomeWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}