/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'community-applications': CommunityApplication;
    'forum-applications': ForumApplication;
    'award-applications': AwardApplication;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'community-applications': CommunityApplicationsSelect<false> | CommunityApplicationsSelect<true>;
    'forum-applications': ForumApplicationsSelect<false> | ForumApplicationsSelect<true>;
    'award-applications': AwardApplicationsSelect<false> | AwardApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'ro' | 'en') | ('ru' | 'ro' | 'en')[];
  globals: {
    'content-common': ContentCommon;
    'content-home': ContentHome;
    'content-forum': ContentForum;
    'content-award': ContentAward;
    'forum-settings': ForumSetting;
    'award-settings': AwardSetting;
    seo: Seo;
    analytics: Analytics;
    mail: Mail;
  };
  globalsSelect: {
    'content-common': ContentCommonSelect<false> | ContentCommonSelect<true>;
    'content-home': ContentHomeSelect<false> | ContentHomeSelect<true>;
    'content-forum': ContentForumSelect<false> | ContentForumSelect<true>;
    'content-award': ContentAwardSelect<false> | ContentAwardSelect<true>;
    'forum-settings': ForumSettingsSelect<false> | ForumSettingsSelect<true>;
    'award-settings': AwardSettingsSelect<false> | AwardSettingsSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>;
    mail: MailSelect<false> | MailSelect<true>;
  };
  locale: 'ru' | 'ro' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Форма на главной странице.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-applications".
 */
export interface CommunityApplication {
  id: number;
  name: string;
  company: string;
  role?: string | null;
  email: string;
  phone?: string | null;
  status?: ('new' | 'progress' | 'accepted' | 'declined') | null;
  /**
   * Видна только в админке.
   */
  note?: string | null;
  lang?: string | null;
  source?: string | null;
  utm?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Форма на странице форума.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-applications".
 */
export interface ForumApplication {
  id: number;
  name: string;
  company: string;
  role?: string | null;
  kind?: string | null;
  email: string;
  phone?: string | null;
  status?: ('new' | 'progress' | 'accepted' | 'declined') | null;
  /**
   * Видна только в админке.
   */
  note?: string | null;
  lang?: string | null;
  source?: string | null;
  utm?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Форма на странице премии — премия отрасли и студенческий конкурс.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-applications".
 */
export interface AwardApplication {
  id: number;
  name: string;
  org: string;
  track?: string | null;
  nomination?: string | null;
  email: string;
  phone?: string | null;
  url?: string | null;
  desc?: string | null;
  status?: ('new' | 'progress' | 'accepted' | 'declined') | null;
  /**
   * Видна только в админке.
   */
  note?: string | null;
  lang?: string | null;
  source?: string | null;
  utm?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'community-applications';
        value: number | CommunityApplication;
      } | null)
    | ({
        relationTo: 'forum-applications';
        value: number | ForumApplication;
      } | null)
    | ({
        relationTo: 'award-applications';
        value: number | AwardApplication;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-applications_select".
 */
export interface CommunityApplicationsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  role?: T;
  email?: T;
  phone?: T;
  status?: T;
  note?: T;
  lang?: T;
  source?: T;
  utm?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-applications_select".
 */
export interface ForumApplicationsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  role?: T;
  kind?: T;
  email?: T;
  phone?: T;
  status?: T;
  note?: T;
  lang?: T;
  source?: T;
  utm?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-applications_select".
 */
export interface AwardApplicationsSelect<T extends boolean = true> {
  name?: T;
  org?: T;
  track?: T;
  nomination?: T;
  email?: T;
  phone?: T;
  url?: T;
  desc?: T;
  status?: T;
  note?: T;
  lang?: T;
  source?: T;
  utm?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Меняется сразу на всех страницах и во всех языках (переключатель локали — вверху справа).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-common".
 */
export interface ContentCommon {
  id: number;
  nav?: {
    /**
     * Сейчас на сайте: «Позиция»
     */
    navPosition?: string | null;
    /**
     * Сейчас на сайте: «Форматы»
     */
    navFormats?: string | null;
    /**
     * Сейчас на сайте: «Форум 2026»
     */
    navForum?: string | null;
    /**
     * Сейчас на сайте: «Премия»
     */
    navAward?: string | null;
    /**
     * Сейчас на сайте: «Участие»
     */
    navParticipation?: string | null;
    /**
     * Сейчас на сайте: «Контакты»
     */
    navContacts?: string | null;
    /**
     * Сейчас на сайте: «Сообщество»
     */
    navCommunity?: string | null;
    /**
     * Сейчас на сайте: «Программа»
     */
    navProgram?: string | null;
    /**
     * Сейчас на сайте: «Заявка»
     */
    navApplication?: string | null;
    /**
     * Сейчас на сайте: «Вступить»
     */
    ctaJoin?: string | null;
    /**
     * Сейчас на сайте: «Подать заявку»
     */
    ctaApply?: string | null;
    /**
     * Сейчас на сайте: «О сообществе»
     */
    ctaAbout?: string | null;
    /**
     * Сейчас на сайте: «листайте»
     */
    scrollHint?: string | null;
  };
  notice?: {
    /**
     * Сейчас на сайте: «Премия отрасли 2026 — приём заявок открыт»
     */
    noticeTitle?: string | null;
    /**
     * Сейчас на сайте: «Подать заявку»
     */
    noticeCta?: string | null;
  };
  contacts?: {
    /**
     * Сейчас на сайте: «marketing@lh47arch.com»
     */
    email1?: string | null;
    /**
     * Сейчас на сайте: «marketing@instylehome.md»
     */
    email2?: string | null;
    /**
     * Сейчас на сайте: «(+373) 68 199 951»
     */
    phone1?: string | null;
    /**
     * Сейчас на сайте: «– InStyle Home»
     */
    phone1Label?: string | null;
    /**
     * Сейчас на сайте: «(+373) 68 059 311»
     */
    phone2?: string | null;
    /**
     * Сейчас на сайте: «– LH47»
     */
    phone2Label?: string | null;
    /**
     * Сейчас на сайте: «Instagram»
     */
    social1?: string | null;
    /**
     * Сейчас на сайте: «Facebook»
     */
    social2?: string | null;
    /**
     * Сейчас на сайте: «LinkedIn»
     */
    social3?: string | null;
  };
  footer?: {
    /**
     * Сейчас на сайте: «Сообщество архитекторов и дизайнеров в Молдове»
     */
    taglineHome?: string | null;
    /**
     * Сейчас на сайте: «Форум и профессиональное сообщество архитектуры, дизайна и девелопмента в Молдове»
     */
    taglineInner?: string | null;
    /**
     * Сейчас на сайте: «Партнёры»
     */
    partners?: string | null;
    /**
     * Сейчас на сайте: «Политика данных»
     */
    privacy?: string | null;
    /**
     * Сейчас на сайте: «© 2026 Future Architecture»
     */
    copyright?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Страница future-arch.md. Пустое поле = остаётся текст, который стоит на сайте сейчас.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-home".
 */
export interface ContentHome {
  id: number;
  hero?: {
    /**
     * Сейчас на сайте: «Est. 2026 · Кишинёв»
     */
    eyebrow?: string | null;
    /**
     * Сейчас на сайте: «Сообщество архитекторов»
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «и дизайнеров в Молдове»
     */
    title2?: string | null;
    /**
     * Сейчас на сайте: «Архитектура и дизайн»
     */
    kicker?: string | null;
    /**
     * Сейчас на сайте: «Вступление по заявке»
     */
    entry?: string | null;
    /**
     * Сейчас на сайте: «Закрытое сообщество.»
     */
    note?: string | null;
  };
  tags?: {
    /**
     * Сейчас на сайте: «Архитектура»
     */
    tagArchitecture?: string | null;
    /**
     * Сейчас на сайте: «Дизайн»
     */
    tagDesign?: string | null;
    /**
     * Сейчас на сайте: «Дизайн интерьера»
     */
    tagInterior?: string | null;
    /**
     * Сейчас на сайте: «Градостроительство»
     */
    tagUrban?: string | null;
    /**
     * Сейчас на сайте: «Независимая практика»
     */
    tagPractice?: string | null;
    /**
     * Сейчас на сайте: «Бюро и студии»
     */
    tagStudios?: string | null;
    /**
     * Сейчас на сайте: «Закрытый круг»
     */
    tagCircle?: string | null;
    /**
     * Сейчас на сайте: «Рекомендации»
     */
    tagRecs?: string | null;
    /**
     * Сейчас на сайте: «ArchiMinds»
     */
    tagArchiminds?: string | null;
    /**
     * Сейчас на сайте: «Экспертиза»
     */
    tagExpertise?: string | null;
    /**
     * Сейчас на сайте: «Нетворкинг»
     */
    tagNetworking?: string | null;
    /**
     * Сейчас на сайте: «Кишинёв»
     */
    tagCity?: string | null;
    /**
     * Сейчас на сайте: «Молдова»
     */
    tagCountry?: string | null;
  };
  position?: {
    /**
     * Это же слово используется в тегах шапки.
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «больше не работает»
     */
    title2?: string | null;
    /**
     * Сейчас на сайте: «в одиночку»
     */
    title3?: string | null;
    /**
     * Сейчас на сайте: «Сильный проект собирает архитектора, девелопера и производителя в одну команду.»
     */
    text?: string | null;
  };
  composition?: {
    /**
     * Сейчас на сайте: «Состав»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «Кто внутри»
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «сообщества»
     */
    title2?: string | null;
    /**
     * Сейчас на сайте: «Резиденты»
     */
    residentsLabel?: string | null;
    /**
     * Сейчас на сайте: «Архитекторы»
     */
    residentsTitle1?: string | null;
    /**
     * Сейчас на сайте: «и дизайнеры»
     */
    residentsTitle2?: string | null;
    /**
     * Сейчас на сайте: «Бюро, студии, частная практика — те, кто проектирует.»
     */
    residentsText?: string | null;
    /**
     * Сейчас на сайте: «Девелоперы, производители, поставщики и бренды»
     */
    partnersTitle?: string | null;
    /**
     * Сейчас на сайте: «Материалы, площадки и производство — доступ для резидентов.»
     */
    partnersText?: string | null;
  };
  formats?: {
    /**
     * Сейчас на сайте: «Инструменты»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «Восемь рабочих»
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «форматов»
     */
    title2?: string | null;
    /**
     * Порядок и количество зафиксированы вёрсткой — меняются названия и описания.
     */
    items?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  forum?: {
    /**
     * Сейчас на сайте: «Главное событие»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «Range Rover Moldova · Кишинёв · 9 декабря 2026»
     */
    venue?: string | null;
    /**
     * Сейчас на сайте: «Future Architecture»
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «Forum»
     */
    title2?: string | null;
    /**
     * Сейчас на сайте: «Один день. Инвестор, девелопер, архитектор и производитель — за одним столом.»
     */
    text?: string | null;
    /**
     * Сейчас на сайте: «250»
     */
    statValue?: string | null;
    /**
     * Сейчас на сайте: «участников»
     */
    statLabel?: string | null;
    /**
     * Сейчас на сайте: «Страница форума»
     */
    cta?: string | null;
  };
  founders?: {
    /**
     * Сейчас на сайте: «Основание»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «Основатели сообщества»
     */
    title?: string | null;
    /**
     * Сейчас на сайте: «Архитектурное бюро LH47 ARCH»
     */
    bureauLabel?: string | null;
    /**
     * Сейчас на сайте: «LH47 arch.»
     */
    bureauName?: string | null;
    stats?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Сейчас на сайте: «Медиа-партнёр»
     */
    mediaLabel?: string | null;
    /**
     * Сейчас на сайте: «InStyle Home»
     */
    mediaName?: string | null;
    /**
     * Сейчас на сайте: «20»
     */
    mediaValue?: string | null;
    /**
     * Сейчас на сайте: «Журнал об архитектуре и интерьере. Публикует проекты участников сообщества.»
     */
    mediaText?: string | null;
  };
  participation?: {
    /**
     * Сейчас на сайте: «Форматы участия»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «Вступление и партнёрство»
     */
    title?: string | null;
    /**
     * Сейчас на сайте: «Резидент»
     */
    residentTitle?: string | null;
    /**
     * Сейчас на сайте: «Архитекторы и дизайнеры»
     */
    residentText?: string | null;
    /**
     * Сейчас на сайте: «Партнёр»
     */
    partnerTitle?: string | null;
    /**
     * Сейчас на сайте: «Условия участия — по запросу»
     */
    terms?: string | null;
    /**
     * Сейчас на сайте: «Запросить условия»
     */
    partnerCta?: string | null;
    /**
     * Сейчас на сайте: «СООБЩЕСТВО»
     */
    sideWord?: string | null;
  };
  form?: {
    /**
     * Сейчас на сайте: «Вступление»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «по заявке и»
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «модерации»
     */
    title2?: string | null;
    /**
     * Сейчас на сайте: «Имя»
     */
    fieldName?: string | null;
    /**
     * Сейчас на сайте: «Компания»
     */
    fieldCompany?: string | null;
    /**
     * Сейчас на сайте: «Например: архитектор, руководитель бюро»
     */
    fieldRoleHint?: string | null;
    /**
     * Сейчас на сайте: «E-mail»
     */
    fieldEmail?: string | null;
    /**
     * Сейчас на сайте: «Телефон»
     */
    fieldPhone?: string | null;
    /**
     * Сейчас на сайте: «Отправить заявку»
     */
    submit?: string | null;
    /**
     * Сейчас на сайте: «Заявка отправлена»
     */
    sentTitle?: string | null;
    /**
     * Сейчас на сайте: «Ответ придёт на указанную почту после модерации.»
     */
    sentText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Дата форума и показ таймера живут в разделе «Форум — настройки». Здесь — тексты.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-forum".
 */
export interface ContentForum {
  id: number;
  hero?: {
    /**
     * Сейчас на сайте: «2026»
     */
    year?: string | null;
    /**
     * Сейчас на сайте: «Кишинёв · Молдова»
     */
    place?: string | null;
    /**
     * Сейчас на сайте: «Закрытый формат · частное мероприятие»
     */
    format?: string | null;
    /**
     * Сейчас на сайте: «Future Architecture»
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «Forum»
     */
    title2?: string | null;
    /**
     * Сейчас на сайте: «Рынку нужен открытый диалог»
     */
    claim?: string | null;
    /**
     * Сейчас на сайте: «Заявка на участие»
     */
    ctaApply?: string | null;
    /**
     * Сейчас на сайте: «Стать партнёром»
     */
    ctaPartner?: string | null;
    /**
     * Сейчас на сайте: «Приём заявок открыт · 9 декабря 2026»
     */
    status?: string | null;
    /**
     * Сейчас на сайте: «до начала форума»
     */
    countdownNote?: string | null;
    /**
     * Сейчас на сайте: «9 декабря 2026 · Кишинёв»
     */
    dateLine?: string | null;
  };
  marquee?: {
    /**
     * Сейчас на сайте: «250+ участников»
     */
    m1?: string | null;
    /**
     * Сейчас на сайте: «по заявке и отбору»
     */
    m2?: string | null;
    /**
     * Сейчас на сайте: «Кишинёв»
     */
    m3?: string | null;
    /**
     * Сейчас на сайте: «9 декабря 2026»
     */
    m4?: string | null;
    /**
     * Сейчас на сайте: «закрытый формат»
     */
    m5?: string | null;
    /**
     * Сейчас на сайте: «Range Rover Moldova»
     */
    m6?: string | null;
    /**
     * Сейчас на сайте: «премия отрасли»
     */
    m7?: string | null;
    /**
     * Сейчас на сайте: «закрытый ужин»
     */
    m8?: string | null;
  };
  chain?: {
    /**
     * Сейчас на сайте: «Задача»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «Цепочка стоимости»
     */
    title?: string | null;
    /**
     * Сейчас на сайте: «Успешный проект — результат работы всей цепочки: от инвестора и владельца земли до архитек…»
     */
    text?: string | null;
    /**
     * Сейчас на сайте: «Шесть этапов жизни объекта — и кто отвечает за каждый»
     */
    note?: string | null;
    /**
     * Сейчас на сайте: «Форум собирает всю цепочку в один день»
     */
    note2?: string | null;
    /**
     * Сейчас на сайте: «Среда»
     */
    tag2?: string | null;
    /**
     * Сейчас на сайте: «Ликвидность»
     */
    tag3?: string | null;
    /**
     * Сейчас на сайте: «Инфраструктура»
     */
    tag4?: string | null;
    /**
     * Сейчас на сайте: «Ценность»
     */
    tag5?: string | null;
    /**
     * Сейчас на сайте: «Контекст»
     */
    tag6?: string | null;
    stages?:
      | {
          title?: string | null;
          role?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  hall?: {
    /**
     * Сейчас на сайте: «Состав зала»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «250»
     */
    statValue?: string | null;
    /**
     * Сейчас на сайте: «участников»
     */
    statLabel?: string | null;
    /**
     * Сейчас на сайте: «по заявке и отбору»
     */
    entry?: string | null;
    groups?:
      | {
          title?: string | null;
          share?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  topics?: {
    /**
     * Сейчас на сайте: «Направления»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «Темы»
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «программы форума»
     */
    title2?: string | null;
    items?:
      | {
          tag?: string | null;
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  program?: {
    /**
     * Сейчас на сайте: «Программа дня»
     */
    title?: string | null;
    /**
     * Сейчас на сайте: «9 декабря 2026 · точное расписание опубликуем позже»
     */
    note?: string | null;
    items?:
      | {
          title?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Сейчас на сайте: «Спикеры»
     */
    speakersTitle?: string | null;
    /**
     * Сейчас на сайте: «Состав дополняется»
     */
    speakersNote?: string | null;
    /**
     * Сейчас на сайте: «Скоро»
     */
    slotTitle?: string | null;
  };
  award?: {
    /**
     * Сейчас на сайте: «отрасли»
     */
    title2?: string | null;
    /**
     * Сейчас на сайте: «Награждаем лучшие проекты, бюро и компании. Вручение — на форуме.»
     */
    text1?: string | null;
    /**
     * Сейчас на сайте: «Конкурс студенческих идей: общественные пространства и облик городов Молдовы.»
     */
    text2?: string | null;
    /**
     * Сейчас на сайте: «Подать проект на премию»
     */
    cta?: string | null;
  };
  participation?: {
    /**
     * Сейчас на сайте: «Участие в форуме»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «Как»
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «участвовать»
     */
    title2?: string | null;
    /**
     * Сейчас на сайте: «01 · по заявке и отбору»
     */
    aLabel?: string | null;
    /**
     * Сейчас на сайте: «Участник»
     */
    aTitle?: string | null;
    /**
     * Сейчас на сайте: «Доступ к 250+ участникам рынка»
     */
    aItem1?: string | null;
    /**
     * Сейчас на сайте: «Темы программы форума»
     */
    aItem2?: string | null;
    /**
     * Сейчас на сайте: «Две сессии выступлений и панельные дискуссии»
     */
    aItem3?: string | null;
    /**
     * Сейчас на сайте: «Обед, фуршет и нетворкинг в течение дня»
     */
    aItem4?: string | null;
    /**
     * Сейчас на сайте: «Заявка на участие»
     */
    aCta?: string | null;
    /**
     * Сейчас на сайте: «02 · партнёрство»
     */
    bLabel?: string | null;
    /**
     * Сейчас на сайте: «Партнёр»
     */
    bTitle?: string | null;
    /**
     * Сейчас на сайте: «Форум — не один день. Партнёр в кампании до, во время и после: анонсы, digital, публикации…»
     */
    bText?: string | null;
    /**
     * Сейчас на сайте: «Прямой контакт с 250 участниками зала»
     */
    bItem1?: string | null;
    /**
     * Сейчас на сайте: «Места закрытого ужина закреплены за партнёрами»
     */
    bItem2?: string | null;
    /**
     * Сейчас на сайте: «Запросить презентацию»
     */
    bCta?: string | null;
    /**
     * Сейчас на сайте: «Позиции партнёрства и полные условия — в презентации»
     */
    bNote?: string | null;
    /**
     * Сейчас на сайте: «Форум создаёт первый контакт. Сообщество делает его рабочим.»
     */
    outro?: string | null;
  };
  form?: {
    /**
     * Сейчас на сайте: «ЗАЯВКА»
     */
    sideWord?: string | null;
    /**
     * Сейчас на сайте: «Участие по заявке и»
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «отбору»
     */
    title2?: string | null;
    /**
     * Сейчас на сайте: «Презентация для партнёров отправляется на почту после заявки.»
     */
    note2?: string | null;
    /**
     * Сейчас на сайте: «Имя»
     */
    fieldName?: string | null;
    /**
     * Сейчас на сайте: «Компания»
     */
    fieldCompany?: string | null;
    /**
     * Сейчас на сайте: «E-mail»
     */
    fieldEmail?: string | null;
    /**
     * Сейчас на сайте: «Телефон»
     */
    fieldPhone?: string | null;
    /**
     * Сейчас на сайте: «Тип обращения»
     */
    fieldKind?: string | null;
    /**
     * Сейчас на сайте: «Выберите»
     */
    selectPlaceholder?: string | null;
    /**
     * Сейчас на сайте: «Архитектор или дизайнер»
     */
    optionArchitect?: string | null;
    /**
     * Сейчас на сайте: «Девелопер или застройщик»
     */
    optionDeveloper?: string | null;
    /**
     * Сейчас на сайте: «Производитель или поставщик»
     */
    optionManufacturer?: string | null;
    /**
     * Сейчас на сайте: «Инвестор или бизнес»
     */
    optionInvestor?: string | null;
    /**
     * Сейчас на сайте: «Отправить заявку»
     */
    submit?: string | null;
    /**
     * Сейчас на сайте: «Заявка отправлена»
     */
    sentTitle?: string | null;
    /**
     * Сейчас на сайте: «Ответ придёт на указанную почту. Презентация для партнёров отправляется в ответном письме.»
     */
    sentText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Номинации, жюри, дедлайн и таймер — в разделе «Премия — настройки». Здесь — тексты страницы.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-award".
 */
export interface ContentAward {
  id: number;
  hero?: {
    /**
     * Сейчас на сайте: «Премия отрасли и студенческий конкурс · Кишинёв»
     */
    eyebrow?: string | null;
    /**
     * Сейчас на сайте: «Future Architecture Forum 2026»
     */
    event?: string | null;
    /**
     * Сейчас на сайте: «Лучшее за год»
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «в архитектуре»
     */
    title2?: string | null;
    /**
     * Сейчас на сайте: «Future Architecture Award»
     */
    leadName?: string | null;
    /**
     * Сейчас на сайте: «— награда проектам, бюро и компаниям отрасли. Для студентов — отдельный конкурс. Победител…»
     */
    leadText?: string | null;
    /**
     * Сейчас на сайте: «Заявки принимаются до 20 ноября»
     */
    deadlineLine?: string | null;
    /**
     * Сейчас на сайте: «осталось до конца приёма заявок»
     */
    countdownNote?: string | null;
    /**
     * Сейчас на сайте: «Подать проект компании»
     */
    ctaCompany?: string | null;
    /**
     * Сейчас на сайте: «Подать студенческую работу»
     */
    ctaStudent?: string | null;
  };
  tracks?: {
    /**
     * Сейчас на сайте: «Участники»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «Кто может подать заявку»
     */
    title?: string | null;
    /**
     * Сейчас на сайте: «Премия отрасли»
     */
    aTitle?: string | null;
    /**
     * Сейчас на сайте: «Для архитектурных бюро, дизайн-студий и профильных компаний — девелоперов, производителей …»
     */
    aText1?: string | null;
    /**
     * Сейчас на сайте: «Принимаем объекты и интерьеры, завершённые за последний год.»
     */
    aText2?: string | null;
    /**
     * Сейчас на сайте: «Студенческий конкурс»
     */
    bTitle?: string | null;
    /**
     * Сейчас на сайте: «Для студентов архитектуры и дизайна.»
     */
    bText1?: string | null;
    /**
     * Сейчас на сайте: «Тема года — общественные пространства и облик городов Молдовы. Подойдут учебные, дипломные…»
     */
    bText2?: string | null;
  };
  nominations?: {
    /**
     * Сейчас на сайте: «Номинации»
     */
    title?: string | null;
    /**
     * Сейчас на сайте: «Именная номинация — в пакете партнёра форума»
     */
    link?: string | null;
  };
  result?: {
    /**
     * Сейчас на сайте: «Награда»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «Что получает победитель»
     */
    title?: string | null;
    /**
     * Сейчас на сайте: «Награду вручают на сцене форума, в зале»
     */
    item1?: string | null;
    /**
     * Сейчас на сайте: «250»
     */
    item1Value?: string | null;
    /**
     * Сейчас на сайте: «человек»
     */
    item1Unit?: string | null;
    /**
     * Сейчас на сайте: «Проект выходит публикацией в InStyle Home»
     */
    item2?: string | null;
    /**
     * Сейчас на сайте: «Фото и видео церемонии — для сайта, соцсетей и презентаций»
     */
    item3?: string | null;
    /**
     * Сейчас на сайте: «Место в сообществе — резидентом или партнёром»
     */
    item4?: string | null;
  };
  how?: {
    /**
     * Сейчас на сайте: «Отбор»
     */
    label?: string | null;
    /**
     * Сейчас на сайте: «Как проходит отбор»
     */
    title?: string | null;
    /**
     * Сейчас на сайте: «Заявка до 20 ноября»
     */
    step1?: string | null;
    /**
     * Сейчас на сайте: «Проверка материалов»
     */
    step2?: string | null;
    /**
     * Сейчас на сайте: «Оценка жюри»
     */
    step3?: string | null;
    /**
     * Сейчас на сайте: «Победители на форуме 9 декабря»
     */
    step4?: string | null;
    /**
     * Сейчас на сайте: «Заявки до 20 ноября»
     */
    marquee1?: string | null;
    /**
     * Сейчас на сайте: «Future Architecture Award 2026»
     */
    marquee2?: string | null;
    /**
     * Сейчас на сайте: «Награждение 9 декабря · Кишинёв»
     */
    marquee3?: string | null;
  };
  form?: {
    /**
     * Сейчас на сайте: «Заявки принимаются»
     */
    title1?: string | null;
    /**
     * Сейчас на сайте: «до 20 ноября»
     */
    title2?: string | null;
    /**
     * Сейчас на сайте: «Имя и фамилия»
     */
    fieldName?: string | null;
    /**
     * Сейчас на сайте: «Компания или учебное заведение»
     */
    fieldOrg?: string | null;
    /**
     * Сейчас на сайте: «Куда подаёте»
     */
    fieldTrack?: string | null;
    /**
     * Сейчас на сайте: «Номинация»
     */
    fieldNomination?: string | null;
    /**
     * Сейчас на сайте: «E-mail»
     */
    fieldEmail?: string | null;
    /**
     * Сейчас на сайте: «Телефон»
     */
    fieldPhone?: string | null;
    /**
     * Сейчас на сайте: «Ссылка на материалы проекта»
     */
    fieldUrl?: string | null;
    /**
     * Сейчас на сайте: «Коротко о проекте»
     */
    fieldDesc?: string | null;
    /**
     * Сейчас на сайте: «Ссылка на облако или портфолио — файлы загружать не нужно»
     */
    hint?: string | null;
    /**
     * Сейчас на сайте: «Отправить заявку»
     */
    submit?: string | null;
    /**
     * Сейчас на сайте: «Заявка отправлена»
     */
    sentTitle?: string | null;
    /**
     * Сейчас на сайте: «Ответ придёт на указанную почту после проверки материалов.»
     */
    sentText?: string | null;
    /**
     * Сейчас на сайте: «Награды вручают на форуме. Сообщество работает между форумами.»
     */
    outro?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Дата форума и обратный отсчёт на всех страницах.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-settings".
 */
export interface ForumSetting {
  id: number;
  /**
   * От неё считается таймер обратного отсчёта и микроразметка события для Google.
   */
  forumDate?: string | null;
  countdownVisible?: boolean | null;
  /**
   * Карточки со знаком вопроса после объявленных спикеров — показывают, что состав ещё собирается. 0 — не показывать.
   */
  speakerSlots?: number | null;
  speakers?:
    | {
        /**
         * В версиях RO и EN можно поставить латиницу.
         */
        name: string;
        /**
         * Короткое название — печатается оранжевым под именем.
         */
        company?: string | null;
        /**
         * Одно-два предложения: должность и чем известен.
         */
        role?: string | null;
        /**
         * Вертикальный кадр 4:5, от 800 px по короткой стороне. Пока фото нет, в карточке стоят инициалы.
         */
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Дедлайн приёма заявок, номинации и жюри. Номинации сразу попадают и в список на странице, и в выпадающий список формы.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-settings".
 */
export interface AwardSetting {
  id: number;
  /**
   * Как дата выглядит в тексте: «Заявки до 20 ноября».
   */
  deadlineLabel?: string | null;
  /**
   * От неё считается таймер.
   */
  deadlineDate?: string | null;
  countdownVisible?: boolean | null;
  /**
   * Снимите галочку, когда приём закрыт: форма заменится сообщением ниже.
   */
  formOpen?: boolean | null;
  formClosedText?: string | null;
  nominations?:
    | {
        /**
         * Двузначный: 01, 02…
         */
        no?: string | null;
        title: string;
        /**
         * Короткая расшифровка. Показывается в списке номинаций под названием.
         */
        hint?: string | null;
        id?: string | null;
      }[]
    | null;
  studentNominations?:
    | {
        /**
         * Двузначный: 01, 02…
         */
        no?: string | null;
        title: string;
        /**
         * Короткая расшифровка. Показывается в списке номинаций под названием.
         */
        hint?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Пока состав не утверждён — держите выключенным.
   */
  juryVisible?: boolean | null;
  jury?:
    | {
        no?: string | null;
        name: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Title и description для поиска и соцсетей. Пустые поля — остаются значения по умолчанию, зашитые в коде.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  /**
   * До 60 знаков. Пусто — берётся заголовок по умолчанию.
   */
  homeTitle?: string | null;
  /**
   * До 160 знаков. Одно предложение с пользой и конкретикой.
   */
  homeDescription?: string | null;
  /**
   * Что видно, когда ссылку кидают в чат. Пусто — общая og.png.
   */
  homeImage?: (number | null) | Media;
  /**
   * До 60 знаков. Пусто — берётся заголовок по умолчанию.
   */
  forumTitle?: string | null;
  /**
   * До 160 знаков. Одно предложение с пользой и конкретикой.
   */
  forumDescription?: string | null;
  /**
   * Что видно, когда ссылку кидают в чат. Пусто — общая og.png.
   */
  forumImage?: (number | null) | Media;
  /**
   * До 60 знаков. Пусто — берётся заголовок по умолчанию.
   */
  awardTitle?: string | null;
  /**
   * До 160 знаков. Одно предложение с пользой и конкретикой.
   */
  awardDescription?: string | null;
  /**
   * Что видно, когда ссылку кидают в чат. Пусто — общая og.png.
   */
  awardImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Идентификаторы вставляются в код всех страниц. Скрипты не грузятся, пока поле пустое, — сайт не тормозит зря.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: number;
  /**
   * Снимите галочку, чтобы временно отключить всю аналитику.
   */
  enabled?: boolean | null;
  /**
   * Контейнер GTM. Если он заполнен, GA4 удобнее подключать внутри GTM, а поле ниже оставить пустым.
   */
  gtmId?: string | null;
  /**
   * Прямое подключение gtag.js — если GTM не используется.
   */
  ga4Id?: string | null;
  /**
   * Только значение content из мета-тега, без самого тега. Нужно один раз, чтобы подтвердить права на сайт.
   */
  searchConsoleToken?: string | null;
  /**
   * Необязательно.
   */
  yandexId?: string | null;
  /**
   * Необязательно — для рекламы в Instagram и Facebook.
   */
  metaPixelId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Каждая отправленная форма сохраняется в разделе «Заявки» и дублируется письмом. Даже если почта не отправится, заявка не потеряется.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail".
 */
export interface Mail {
  id: number;
  /**
   * Несколько адресов — через запятую.
   */
  to: string;
  /**
   * По нему удобно ставить фильтр в почте.
   */
  subjectPrefix?: string | null;
  autoreply?: boolean | null;
  autoreplySubject?: string | null;
  /**
   * Обычный текст. Абзацы — пустой строкой.
   */
  autoreplyBody?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-common_select".
 */
export interface ContentCommonSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        navPosition?: T;
        navFormats?: T;
        navForum?: T;
        navAward?: T;
        navParticipation?: T;
        navContacts?: T;
        navCommunity?: T;
        navProgram?: T;
        navApplication?: T;
        ctaJoin?: T;
        ctaApply?: T;
        ctaAbout?: T;
        scrollHint?: T;
      };
  notice?:
    | T
    | {
        noticeTitle?: T;
        noticeCta?: T;
      };
  contacts?:
    | T
    | {
        email1?: T;
        email2?: T;
        phone1?: T;
        phone1Label?: T;
        phone2?: T;
        phone2Label?: T;
        social1?: T;
        social2?: T;
        social3?: T;
      };
  footer?:
    | T
    | {
        taglineHome?: T;
        taglineInner?: T;
        partners?: T;
        privacy?: T;
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-home_select".
 */
export interface ContentHomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title1?: T;
        title2?: T;
        kicker?: T;
        entry?: T;
        note?: T;
      };
  tags?:
    | T
    | {
        tagArchitecture?: T;
        tagDesign?: T;
        tagInterior?: T;
        tagUrban?: T;
        tagPractice?: T;
        tagStudios?: T;
        tagCircle?: T;
        tagRecs?: T;
        tagArchiminds?: T;
        tagExpertise?: T;
        tagNetworking?: T;
        tagCity?: T;
        tagCountry?: T;
      };
  position?:
    | T
    | {
        title1?: T;
        title2?: T;
        title3?: T;
        text?: T;
      };
  composition?:
    | T
    | {
        label?: T;
        title1?: T;
        title2?: T;
        residentsLabel?: T;
        residentsTitle1?: T;
        residentsTitle2?: T;
        residentsText?: T;
        partnersTitle?: T;
        partnersText?: T;
      };
  formats?:
    | T
    | {
        label?: T;
        title1?: T;
        title2?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  forum?:
    | T
    | {
        label?: T;
        venue?: T;
        title1?: T;
        title2?: T;
        text?: T;
        statValue?: T;
        statLabel?: T;
        cta?: T;
      };
  founders?:
    | T
    | {
        label?: T;
        title?: T;
        bureauLabel?: T;
        bureauName?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        mediaLabel?: T;
        mediaName?: T;
        mediaValue?: T;
        mediaText?: T;
      };
  participation?:
    | T
    | {
        label?: T;
        title?: T;
        residentTitle?: T;
        residentText?: T;
        partnerTitle?: T;
        terms?: T;
        partnerCta?: T;
        sideWord?: T;
      };
  form?:
    | T
    | {
        label?: T;
        title1?: T;
        title2?: T;
        fieldName?: T;
        fieldCompany?: T;
        fieldRoleHint?: T;
        fieldEmail?: T;
        fieldPhone?: T;
        submit?: T;
        sentTitle?: T;
        sentText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-forum_select".
 */
export interface ContentForumSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        year?: T;
        place?: T;
        format?: T;
        title1?: T;
        title2?: T;
        claim?: T;
        ctaApply?: T;
        ctaPartner?: T;
        status?: T;
        countdownNote?: T;
        dateLine?: T;
      };
  marquee?:
    | T
    | {
        m1?: T;
        m2?: T;
        m3?: T;
        m4?: T;
        m5?: T;
        m6?: T;
        m7?: T;
        m8?: T;
      };
  chain?:
    | T
    | {
        label?: T;
        title?: T;
        text?: T;
        note?: T;
        note2?: T;
        tag2?: T;
        tag3?: T;
        tag4?: T;
        tag5?: T;
        tag6?: T;
        stages?:
          | T
          | {
              title?: T;
              role?: T;
              id?: T;
            };
      };
  hall?:
    | T
    | {
        label?: T;
        statValue?: T;
        statLabel?: T;
        entry?: T;
        groups?:
          | T
          | {
              title?: T;
              share?: T;
              id?: T;
            };
      };
  topics?:
    | T
    | {
        label?: T;
        title1?: T;
        title2?: T;
        items?:
          | T
          | {
              tag?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  program?:
    | T
    | {
        title?: T;
        note?: T;
        items?:
          | T
          | {
              title?: T;
              id?: T;
            };
        speakersTitle?: T;
        speakersNote?: T;
        slotTitle?: T;
      };
  award?:
    | T
    | {
        title2?: T;
        text1?: T;
        text2?: T;
        cta?: T;
      };
  participation?:
    | T
    | {
        label?: T;
        title1?: T;
        title2?: T;
        aLabel?: T;
        aTitle?: T;
        aItem1?: T;
        aItem2?: T;
        aItem3?: T;
        aItem4?: T;
        aCta?: T;
        bLabel?: T;
        bTitle?: T;
        bText?: T;
        bItem1?: T;
        bItem2?: T;
        bCta?: T;
        bNote?: T;
        outro?: T;
      };
  form?:
    | T
    | {
        sideWord?: T;
        title1?: T;
        title2?: T;
        note2?: T;
        fieldName?: T;
        fieldCompany?: T;
        fieldEmail?: T;
        fieldPhone?: T;
        fieldKind?: T;
        selectPlaceholder?: T;
        optionArchitect?: T;
        optionDeveloper?: T;
        optionManufacturer?: T;
        optionInvestor?: T;
        submit?: T;
        sentTitle?: T;
        sentText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-award_select".
 */
export interface ContentAwardSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        event?: T;
        title1?: T;
        title2?: T;
        leadName?: T;
        leadText?: T;
        deadlineLine?: T;
        countdownNote?: T;
        ctaCompany?: T;
        ctaStudent?: T;
      };
  tracks?:
    | T
    | {
        label?: T;
        title?: T;
        aTitle?: T;
        aText1?: T;
        aText2?: T;
        bTitle?: T;
        bText1?: T;
        bText2?: T;
      };
  nominations?:
    | T
    | {
        title?: T;
        link?: T;
      };
  result?:
    | T
    | {
        label?: T;
        title?: T;
        item1?: T;
        item1Value?: T;
        item1Unit?: T;
        item2?: T;
        item3?: T;
        item4?: T;
      };
  how?:
    | T
    | {
        label?: T;
        title?: T;
        step1?: T;
        step2?: T;
        step3?: T;
        step4?: T;
        marquee1?: T;
        marquee2?: T;
        marquee3?: T;
      };
  form?:
    | T
    | {
        title1?: T;
        title2?: T;
        fieldName?: T;
        fieldOrg?: T;
        fieldTrack?: T;
        fieldNomination?: T;
        fieldEmail?: T;
        fieldPhone?: T;
        fieldUrl?: T;
        fieldDesc?: T;
        hint?: T;
        submit?: T;
        sentTitle?: T;
        sentText?: T;
        outro?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-settings_select".
 */
export interface ForumSettingsSelect<T extends boolean = true> {
  forumDate?: T;
  countdownVisible?: T;
  speakerSlots?: T;
  speakers?:
    | T
    | {
        name?: T;
        company?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-settings_select".
 */
export interface AwardSettingsSelect<T extends boolean = true> {
  deadlineLabel?: T;
  deadlineDate?: T;
  countdownVisible?: T;
  formOpen?: T;
  formClosedText?: T;
  nominations?:
    | T
    | {
        no?: T;
        title?: T;
        hint?: T;
        id?: T;
      };
  studentNominations?:
    | T
    | {
        no?: T;
        title?: T;
        hint?: T;
        id?: T;
      };
  juryVisible?: T;
  jury?:
    | T
    | {
        no?: T;
        name?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  homeTitle?: T;
  homeDescription?: T;
  homeImage?: T;
  forumTitle?: T;
  forumDescription?: T;
  forumImage?: T;
  awardTitle?: T;
  awardDescription?: T;
  awardImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  enabled?: T;
  gtmId?: T;
  ga4Id?: T;
  searchConsoleToken?: T;
  yandexId?: T;
  metaPixelId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail_select".
 */
export interface MailSelect<T extends boolean = true> {
  to?: T;
  subjectPrefix?: T;
  autoreply?: T;
  autoreplySubject?: T;
  autoreplyBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}